# Generated by Django 6.0.2 on 2026-02-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Duyuru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("baslik", models.CharField(blank=True, max_length=120, verbose_name="Başlık")),
                ("metin", models.TextField(verbose_name="Duyuru Metni")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "baslangic",
                    models.DateTimeField(blank=True, null=True, verbose_name="Başlangıç"),
                ),
                ("bitis", models.DateTimeField(blank=True, null=True, verbose_name="Bitiş")),
                ("sira", models.PositiveIntegerField(default=10, verbose_name="Sıra")),
                ("etiket", models.CharField(blank=True, max_length=32, verbose_name="Etiket")),
                ("olusturma", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturma")),
                ("guncelleme", models.DateTimeField(auto_now=True, verbose_name="Güncelleme")),
            ],
            options={
                "verbose_name": "Duyuru",
                "verbose_name_plural": "Duyurular",
                "ordering": ["sira", "-olusturma"],
            },
        ),
        migrations.CreateModel(
            name="Etkinlik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("baslik", models.CharField(max_length=200, verbose_name="Başlık")),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                ("baslangic", models.DateTimeField(verbose_name="Başlangıç")),
                ("bitis", models.DateTimeField(blank=True, null=True, verbose_name="Bitiş")),
                ("yer", models.CharField(blank=True, max_length=200, verbose_name="Yer")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "afis",
                    models.ImageField(
                        blank=True, null=True, upload_to="afisler/", verbose_name="Afiş"
                    ),
                ),
                ("olusturma", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturma")),
                ("guncelleme", models.DateTimeField(auto_now=True, verbose_name="Güncelleme")),
            ],
            options={
                "verbose_name": "Etkinlik",
                "verbose_name_plural": "Etkinlikler",
                "ordering": ["baslangic"],
            },
        ),
        migrations.CreateModel(
            name="KioskAyar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ana_sayfa_sure",
                    models.PositiveIntegerField(
                        default=15, help_text="Ana sayfa ekranda kaç saniye kalsın?"
                    ),
                ),
                (
                    "etkinlik_sure",
                    models.PositiveIntegerField(
                        default=15, help_text="Etkinlikler ekranda kaç saniye kalsın?"
                    ),
                ),
                (
                    "efekt",
                    models.CharField(
                        choices=[("fade", "Fade"), ("slide", "Slide")],
                        default="fade",
                        max_length=10,
                    ),
                ),
                ("aktif", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kiosk Ayarı",
                "verbose_name_plural": "Kiosk Ayarları",
            },
        ),
        migrations.CreateModel(
            name="DersSaati",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "gun",
                    models.IntegerField(
                        choices=[
                            (1, "Pazartesi"),
                            (2, "Salı"),
                            (3, "Çarşamba"),
                            (4, "Perşembe"),
                            (5, "Cuma"),
                            (6, "Cumartesi"),
                            (7, "Pazar"),
                        ],
                        verbose_name="Gün",
                    ),
                ),
                ("ders_no", models.PositiveSmallIntegerField(verbose_name="Ders No")),
                ("baslangic", models.TimeField(verbose_name="Başlangıç Saati")),
                ("sure_dk", models.PositiveSmallIntegerField(default=40, verbose_name="Süre (dk)")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Ders Saati",
                "verbose_name_plural": "Ders Saatleri",
                "ordering": ["gun", "ders_no"],
                "unique_together": {("gun", "ders_no")},
            },
        ),
    ]
