# Generated by Django 6.0.2 on 2026-02-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pano", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedyaIcerik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(blank=True, max_length=100, verbose_name="Başlık"),
                ),
                (
                    "dosya",
                    models.FileField(upload_to="medya_icerik/", verbose_name="Dosya"),
                ),
                (
                    "tur",
                    models.CharField(
                        choices=[("image", "Resim"), ("video", "Video")],
                        default="image",
                        max_length=10,
                        verbose_name="Tür",
                    ),
                ),
                (
                    "sure",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Resimler için gösterim süresi. Videolar kendi süresince oynar.",
                        verbose_name="Süre (sn)",
                    ),
                ),
                ("sira", models.PositiveIntegerField(default=10, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                ("olusturma", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Medya İçerik",
                "verbose_name_plural": "Medya İçerikleri",
                "ordering": ["sira", "-olusturma"],
            },
        ),
    ]
