# Generated by Django 6.0.2 on 2026-02-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pano", "0002_medyaicerik"),
    ]

    operations = [
        migrations.AddField(
            model_name="medyaicerik",
            name="aciklama",
            field=models.TextField(blank=True, verbose_name="Açıklama"),
        ),
    ]
