# Generated by Django 6.0.3 on 2026-05-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pano", "0003_medyaicerik_aciklama"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskayar",
            name="etkinlik_sayfasi",
            field=models.BooleanField(
                default=True,
                help_text="Kapalıysa /pano/etkinlikler/ sayfasına geçiş yapılmaz.",
                verbose_name="Etkinlikler sayfası",
            ),
        ),
    ]
