# Generated by Django 6.0.3 on 2026-07-26 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ogrenci', '0013_ogrenci_aktif'),
        ('okul', '0018_alter_personel_durum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeneSonuGecisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_zamani', models.DateTimeField(default=django.utils.timezone.now)),
                ('uygulandi', models.BooleanField(default=False, verbose_name='Uygulandı')),
                ('uygulama_zamani', models.DateTimeField(blank=True, null=True, verbose_name='Uygulama Zamanı')),
                ('eski_egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sene_sonu_gecisleri_eski', to='okul.egitimogretimyili', verbose_name='Eski Eğitim-Öğretim Yılı')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sene_sonu_gecisleri', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('yeni_egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sene_sonu_gecisleri_yeni', to='okul.egitimogretimyili', verbose_name='Yeni Eğitim-Öğretim Yılı')),
            ],
            options={
                'verbose_name': 'Sene Sonu Geçişi',
                'verbose_name_plural': 'Sene Sonu Geçişleri',
                'db_table': 'senesonu_gecisi',
                'ordering': ['-olusturulma_zamani'],
            },
        ),
        migrations.CreateModel(
            name='SeneSonuOgrenciGecisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eski_sinif', models.IntegerField(verbose_name='Eski Sınıf')),
                ('eski_sube', models.CharField(max_length=2, verbose_name='Eski Şube')),
                ('yeni_sinif', models.IntegerField(blank=True, null=True, verbose_name='Yeni Sınıf')),
                ('yeni_sube', models.CharField(blank=True, max_length=2, verbose_name='Yeni Şube')),
                ('durum', models.CharField(choices=[('normal', 'Normal Geçiş'), ('sinif_tekrari', 'Sınıf Tekrarı'), ('mezun', 'Mezun'), ('inceleme_gerekli', 'İnceleme Gerekli')], max_length=20, verbose_name='Durum')),
                ('gecis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogrenci_gecisleri', to='senesonu.senesonugecisi', verbose_name='Sene Sonu Geçişi')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sene_sonu_gecisleri', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Sene Sonu Öğrenci Geçişi',
                'verbose_name_plural': 'Sene Sonu Öğrenci Geçişleri',
                'db_table': 'senesonu_ogrenci_gecisi',
                'ordering': ['eski_sinif', 'eski_sube', 'ogrenci__okulno'],
                'unique_together': {('gecis', 'ogrenci')},
            },
        ),
    ]
