# Generated by Django 6.0.3 on 2026-03-14 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nobet", "0009_okulbilgi"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Duyuru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Duyuru Tarihi")),
                (
                    "ders_saati",
                    models.PositiveSmallIntegerField(verbose_name="Ders Saati"),
                ),
                ("mesaj", models.TextField(verbose_name="Duyuru Mesajı")),
                ("olusturulma_zaman", models.DateTimeField(auto_now_add=True)),
                (
                    "olusturan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "sinif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duyurular",
                        to="nobet.sinifsube",
                        verbose_name="Sınıf/Şube",
                    ),
                ),
            ],
            options={
                "verbose_name": "Duyuru",
                "verbose_name_plural": "Duyurular",
                "ordering": ["-tarih", "ders_saati"],
            },
        ),
    ]
