# Generated by Django 6.0.3 on 2026-03-27 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nobet", "0017_okul_donem_egitim_yili_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MudurYardimcisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aktif",
                    models.BooleanField(
                        default=True,
                        help_text="Pasif yapılırsa yetki kontrolü reddeder.",
                        verbose_name="Aktif",
                    ),
                ),
                (
                    "personel",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mudur_yardimcisi",
                        to="nobet.nobetpersonel",
                        verbose_name="Personel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mudur_yardimcisi",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Müdür Yardımcısı",
                "verbose_name_plural": "Müdür Yardımcıları",
            },
        ),
    ]
