# Generated by Django 6.0.3 on 2026-03-27 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okul", "0009_rename_nobetpersonel_to_personel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VeriAktarimGecmisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dosya_turu",
                    models.CharField(
                        choices=[
                            ("ders_programi", "Haftalık Ders Programı"),
                            ("nobet_listesi", "Nöbet Listesi"),
                            ("ogrenci_listesi", "Öğrenci Listesi"),
                            ("personel_listesi", "Personel Listesi"),
                        ],
                        max_length=20,
                        verbose_name="Dosya Türü",
                    ),
                ),
                (
                    "dosya_adi",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dosya Adı"
                    ),
                ),
                (
                    "uygulama_tarihi",
                    models.DateField(
                        blank=True,
                        help_text="Verinin geçerli olduğu tarih (haftalık program / nöbet listesi için)",
                        null=True,
                        verbose_name="Uygulama Tarihi",
                    ),
                ),
                (
                    "dosya_tarihi",
                    models.DateField(
                        blank=True,
                        help_text="e-Okul'dan alınan dosyanın ait olduğu tarih (öğrenci listesi için)",
                        null=True,
                        verbose_name="Dosya Tarihi",
                    ),
                ),
                (
                    "yukleme_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yükleme Tarihi"
                    ),
                ),
                (
                    "kayit_sayisi",
                    models.PositiveIntegerField(
                        default=0, verbose_name="İşlenen Kayıt"
                    ),
                ),
                (
                    "hata_sayisi",
                    models.PositiveIntegerField(default=0, verbose_name="Hatalı Kayıt"),
                ),
                (
                    "otomatik_eklenen",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sistemde bulunmayıp otomatik oluşturulan kayıt sayısı",
                        verbose_name="Otomatik Eklenen",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("basarili", "Başarılı"),
                            ("kismi", "Kısmi (uyarılarla tamamlandı)"),
                            ("hatali", "Hatalı"),
                        ],
                        default="basarili",
                        max_length=10,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "notlar",
                    models.TextField(
                        blank=True,
                        help_text="Uyarılar, otomatik oluşturulan isimler vb.",
                        verbose_name="Notlar",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veri_aktarimlari",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yükleyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veri Aktarım Kaydı",
                "verbose_name_plural": "Veri Aktarım Geçmişi",
                "db_table": "okul_veri_aktarim_gecmisi",
                "ordering": ["-yukleme_tarihi"],
            },
        ),
    ]
