# Generated by Django 6.0.3 on 2026-03-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okul", "0010_add_veri_aktarim_gecmisi"),
    ]

    operations = [
        migrations.AddField(
            model_name="dershavuzu",
            name="cift_oturum",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Yazılı"), (1, "Yazılı + Uygulama")],
                default=0,
                verbose_name="Sınav Türü",
            ),
        ),
        migrations.AddField(
            model_name="dershavuzu",
            name="sinav_yapilmayacak",
            field=models.BooleanField(
                default=False,
                help_text="Bu dersten ortak sınav yapılmaz (Beden Eğitimi, Müzik vb.)",
                verbose_name="Sınav Yapılmayacak",
            ),
        ),
    ]
