# Generated by Django 6.0.3 on 2026-04-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okul", "0011_add_dershavuzu_sinav_alanlari"),
    ]

    operations = [
        migrations.CreateModel(
            name="AktifVeriKonfigurasyonu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "veri_turu",
                    models.CharField(
                        choices=[
                            ("ders_programi", "Haftalık Ders Programı"),
                            ("personel_listesi", "Personel Listesi"),
                            ("nobet_listesi", "Nöbet Listesi"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Veri Türü",
                    ),
                ),
                (
                    "uygulama_tarihi",
                    models.DateField(verbose_name="Aktif Uygulama Tarihi"),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Aktif Veri Konfigürasyonu",
                "verbose_name_plural": "Aktif Veri Konfigürasyonları",
                "db_table": "okul_aktif_veri_konfigurasyonu",
            },
        ),
    ]
