# Generated by Django 6.0.3 on 2026-07-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0013_brans_and_personel_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='durum',
            field=models.CharField(choices=[('Görevde', 'Görevde'), ('Dış Görevde', 'Dış Görevde'), ('Aylıksız İzinli', 'Aylıksız İzinli'), ('Analık İzinli', 'Analık İzinli')], default='Görevde', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='gorev_tipi',
            field=models.CharField(blank=True, choices=[('Öğretmen', 'Öğretmen'), ('Müdür', 'Müdür'), ('Okul Müdürü', 'Okul Müdürü'), ('Müdür Yardımcısı', 'Müdür Yardımcısı'), ('Ücretli Öğretmen', 'Ücretli Öğretmen'), ('Görevlendirme', 'Görevlendirme'), ('Rehberlik', 'Rehberlik'), ('YEĞİTEK Okul Sorumlusu', 'YEĞİTEK Okul Sorumlusu')], max_length=50, null=True, verbose_name='Görevi'),
        ),
    ]
