# Generated by Django 6.0.3 on 2026-07-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0015_drop_bildirim_gonderici_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='OgretmenlikAlanCizelgesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.PositiveSmallIntegerField(help_text='Çizelgedeki SIRA NO sütunu (aynı sıra no birden fazla branşı kapsayabilir).', verbose_name='Sıra No')),
                ('brans', models.CharField(max_length=200, verbose_name='Atamaya Esas Olan Alan (Branş)')),
                ('mezunokul', models.CharField(blank=True, max_length=300, verbose_name='Mezun Olduğu Yükseköğretim Programı/Fakülte')),
                ('dersler', models.TextField(verbose_name='Okutacağı Dersler')),
                ('kaynak_sayfa', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kaynak PDF Sayfası')),
            ],
            options={
                'verbose_name': 'Öğretmenlik Alanı Çizelgesi (TTKB)',
                'verbose_name_plural': 'Öğretmenlik Alanları Çizelgesi (TTKB)',
                'db_table': 'okul_ttkb_ogretmenlik_alan_cizelgesi',
                'ordering': ['sira_no', 'brans', 'mezunokul'],
                'unique_together': {('sira_no', 'brans', 'mezunokul')},
            },
        ),
    ]
