# Generated by Django 6.0.3 on 2026-07-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0016_ogretmenlikalancizelgesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='mezunokul',
            field=models.CharField(blank=True, max_length=300, verbose_name='Mezun Olduğu Yükseköğretim Programı/Fakülte'),
        ),
    ]
