# Generated by Django 6.0.3 on 2026-07-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0017_personel_mezunokul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='durum',
            field=models.CharField(choices=[('Görevde', 'Görevde'), ('Dış Görevde', 'Dış Görevde'), ('Aylıksız İzinli', 'Aylıksız İzinli'), ('Analık İzinli', 'Analık İzinli'), ('Görevlendirme Sona Erdi', 'Görevlendirme Sona Erdi'), ('Emekli', 'Emekli'), ('Ayrıldı-Tayin', 'Ayrıldı-Tayin'), ('Açığa Alındı', 'Açığa Alındı')], default='Görevde', max_length=30, verbose_name='Durum'),
        ),
    ]
