# Generated by Django 6.0.3 on 2026-07-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0018_alter_personel_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinifsube',
            name='acik',
            field=models.BooleanField(default=True, help_text='Kapalı şubelere yeni öğrenci atanamaz.', verbose_name='Açık'),
        ),
    ]
