# Generated by Django 6.0.3 on 2026-08-15 19:58 — elle düzenlendi: CreateModel →
# veri taşıma (RunPython) → RemoveField sırası korunmalı (bkz. yorum aşağıda).

import django.db.models.deletion
from django.db import migrations, models


def _acik_degerini_tasi(apps, schema_editor):
    """Her SinifSube için mevcut (tekil) `acik` değerini, o anki AKTİF eğitim-öğretim
    yılına ait bir SinifSubeYil kaydına taşır. Aktif yıl tanımlı değilse (OkulBilgi
    hiç kurulmamışsa) taşınacak bir şey yoktur — atlanır; yeni sistemde açık/kapalı
    durumu zaten yıl bazlı olarak elle girilecektir.
    """
    SinifSube = apps.get_model("okul", "SinifSube")
    SinifSubeYil = apps.get_model("okul", "SinifSubeYil")
    OkulBilgi = apps.get_model("okul", "OkulBilgi")

    okul = OkulBilgi.objects.select_related("okul_egtyil").first()
    aktif_yil = okul.okul_egtyil if okul else None
    if aktif_yil is None:
        return

    SinifSubeYil.objects.bulk_create(
        [
            SinifSubeYil(sinif_sube=ss, egitim_yili=aktif_yil, acik=ss.acik)
            for ss in SinifSube.objects.all()
        ],
        ignore_conflicts=True,
    )


def _geri_al(apps, schema_editor):
    """Tersine alma: veri taşıma tersinemez (RemoveField zaten geri gelecek alanı
    varsayılan değerle dolduracak) — burada yapılacak bir şey yok."""


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0019_sinifsube_acik'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinifSubeYil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acik', models.BooleanField(default=True, help_text='Kapalı şubelere bu yıl için yeni öğrenci atanamaz.', verbose_name='Açık')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinif_sube_durumlari', to='okul.egitimogretimyili', verbose_name='Eğitim-Öğretim Yılı')),
                ('sinif_sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yil_durumlari', to='okul.sinifsube', verbose_name='Sınıf Şube')),
            ],
            options={
                'verbose_name': 'Sınıf Şube — Yıl Durumu',
                'verbose_name_plural': 'Sınıf Şube Yıl Durumları',
                'db_table': 'nobet_sinifsubeyil',
                'ordering': ['-egitim_yili__egitim_baslangic'],
                'unique_together': {('sinif_sube', 'egitim_yili')},
            },
        ),
        migrations.RunPython(_acik_degerini_tasi, _geri_al),
        migrations.RemoveField(
            model_name='sinifsube',
            name='acik',
        ),
    ]
