# Generated by Django 6.0.3 on 2026-08-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0020_sinifsubeyil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktifverikonfigurasyonu',
            name='veri_turu',
            field=models.CharField(choices=[('ders_programi', 'Haftalık Ders Programı'), ('personel_listesi', 'Personel Listesi'), ('nobet_listesi', 'Nöbet Listesi'), ('sinif_sube', 'Sınıf/Şube Listesi')], max_length=20, unique=True, verbose_name='Veri Türü'),
        ),
    ]
