# Generated by Django 6.0.3 on 2026-08-16 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0021_alter_aktifverikonfigurasyonu_veri_turu'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='ogretmenlik_alani',
            field=models.ForeignKey(blank=True, help_text='Branş + mezun olduğu program üzerinden okutabileceği dersleri belirleyen TTKB çizelgesi satırı. Boş bırakılırsa branş/mezunokul otomatik eşleştirilmeye çalışılır (bkz. okul/services/ogretmenlik_alani.py); eşleşme belirsizse (mezunokul metni çizelgeyle birebir uyuşmuyorsa) burada elle seçilmelidir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personeller', to='okul.ogretmenlikalancizelgesi', verbose_name='Okutma Yetkisi (TTKB Eşleştirmesi)'),
        ),
    ]
