# Generated by Django 6.0.3 on 2026-09-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0022_personel_ogretmenlik_alani'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brans',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
