# Generated by Django 6.0.3 on 2026-03-22 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nobet", "0012_remove_devamsizlik"),
        ("ogrenci", "0005_alter_ogrenci_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DersDefteri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tarih",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Tarih"
                    ),
                ),
                ("ders_adi", models.CharField(max_length=100, verbose_name="Ders Adı")),
                (
                    "ders_saati",
                    models.PositiveSmallIntegerField(verbose_name="Ders Saati No"),
                ),
                ("giris_saat", models.TimeField(verbose_name="Giriş Saati")),
                ("cikis_saat", models.TimeField(verbose_name="Çıkış Saati")),
                (
                    "icerik",
                    models.TextField(
                        blank=True, verbose_name="İşlenen Konu / Ders Planı"
                    ),
                ),
                ("olusturma_zamani", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_zamani", models.DateTimeField(auto_now=True)),
                (
                    "devamsiz_ogrenciler",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dersdefteri_kayitlari",
                        to="ogrenci.ogrenci",
                        verbose_name="Devamsız Öğrenciler",
                    ),
                ),
                (
                    "ogretmen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ders_defterleri",
                        to="nobet.nobetpersonel",
                        verbose_name="Öğretmen",
                    ),
                ),
                (
                    "sinif_sube",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ders_defterleri",
                        to="nobet.sinifsube",
                        verbose_name="Sınıf / Şube",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ders Defteri Kaydı",
                "verbose_name_plural": "Ders Defteri",
                "db_table": "dersdefteri",
                "ordering": ["-tarih", "ders_saati"],
                "unique_together": {("ogretmen", "tarih", "sinif_sube", "ders_saati")},
            },
        ),
    ]
