# Generated by Django 6.0.3 on 2026-03-27 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dersdefteri", "0003_update_nobetpersonel_fk_to_okul"),
        ("okul", "0004_add_ders_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="dersdefteri",
            name="ders_saati_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dersdefteri",
                to="okul.derssaatleri",
                verbose_name="Ders Saati",
            ),
        ),
    ]
