# Generated by Django 6.0.3 on 2026-03-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dersdefteri", "0006_replace_ders_saati_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dersdefteri",
            options={
                "ordering": ["-tarih", "ders_saati__derssaati_no"],
                "verbose_name": "Ders Defteri Kaydı",
                "verbose_name_plural": "Ders Defteri",
            },
        ),
    ]
