# Generated by Django 6.0.3 on 2026-05-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ogrenci", "0010_okulno_charfield_to_positiveinteger"),
        ("secmelidersler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sinif_seviyesi",
                    models.IntegerField(
                        choices=[(11, "11. Sınıf"), (12, "12. Sınıf")],
                        verbose_name="Sınıf Seviyesi",
                    ),
                ),
                ("adi", models.CharField(max_length=50, verbose_name="Alan Adı")),
                (
                    "sira",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Sıra"),
                ),
            ],
            options={
                "verbose_name": "Alan",
                "verbose_name_plural": "Alanlar",
                "ordering": ["sinif_seviyesi", "sira"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="ogrencisecim",
            name="uniq_ogrenci_ders",
        ),
        migrations.AlterUniqueTogether(
            name="ogrencisecim",
            unique_together={("ogrenci", "ders")},
        ),
        migrations.AddField(
            model_name="alan",
            name="dersler",
            field=models.ManyToManyField(
                blank=True,
                related_name="alanlar",
                to="secmelidersler.secmeliders",
                verbose_name="Seçmeli Dersler",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alan",
            unique_together={("sinif_seviyesi", "adi")},
        ),
    ]
