# Generated by Django 6.0.3 on 2026-05-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secmelidersler", "0004_havuz_ders_modeli"),
    ]

    operations = [
        migrations.AddField(
            model_name="secmelidershavuzu",
            name="derssaati",
            field=models.CharField(
                default="",
                help_text="Virgülle ayrılmış saat seçenekleri. Örn: '4' veya '2,4' veya '1,2,3'",
                max_length=50,
                verbose_name="Ders Saati",
            ),
        ),
        migrations.AddField(
            model_name="secmelidershavuzu",
            name="secimsayisi",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Öğrencinin bu dersi kaç defa seçebileceği (genellikle 1).",
                verbose_name="Seçim Sayısı",
            ),
        ),
    ]
