# Generated by Django 6.0.3 on 2026-05-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secmelidersler", "0005_havuz_derssaati_secimsayisi"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrtakDersHavuzu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ders_adi",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Ders Adı"
                    ),
                ),
                (
                    "sira",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Sıra"),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Ortak Ders (Havuz)",
                "verbose_name_plural": "Ortak Ders Havuzu",
                "ordering": ["sira", "ders_adi"],
            },
        ),
    ]
