# Generated by Django 6.0.3 on 2026-05-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secmelidersler", "0006_ortak_ders_havuzu_modeli"),
    ]

    operations = [
        migrations.AddField(
            model_name="ortakdershavuzu",
            name="derssaati",
            field=models.CharField(
                default="",
                help_text="Virgülle ayrılmış saat seçenekleri. Örn: '4' veya '2,4' veya '1,2,3'",
                max_length=50,
                verbose_name="Ders Saati",
            ),
        ),
    ]
