# Generated by Django 6.0.3 on 2026-05-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secmelidersler", "0008_remove_ogrencisecim"),
    ]

    operations = [
        migrations.CreateModel(
            name="SinifSeviyeToplamSaat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sinif_seviyesi",
                    models.IntegerField(
                        choices=[
                            (9, "9. Sınıf"),
                            (10, "10. Sınıf"),
                            (11, "11. Sınıf"),
                            (12, "12. Sınıf"),
                        ],
                        unique=True,
                        verbose_name="Sınıf Seviyesi",
                    ),
                ),
                (
                    "haftalik_toplam_saat",
                    models.PositiveSmallIntegerField(
                        default=40,
                        help_text="Bu sınıf seviyesindeki haftalık toplam ders saati (genellikle 40).",
                        verbose_name="Haftalık Toplam Saat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sınıf Seviyesi Toplam Saat",
                "verbose_name_plural": "Sınıf Seviyesi Toplam Saatler",
                "ordering": ["sinif_seviyesi"],
            },
        ),
    ]
