# Generated by Django 6.0.3 on 2026-05-28 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okul", "0012_add_aktif_veri_konfigurasyonu"),
        ("secmelidersler", "0011_rehberlik_verisi"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="alan",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="alan",
            name="egitim_yili",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alanlar",
                to="okul.egitimogretimyili",
                verbose_name="Eğitim-Öğretim Yılı",
            ),
        ),
        migrations.AddField(
            model_name="ortakders",
            name="egitim_yili",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ortak_dersler",
                to="okul.egitimogretimyili",
                verbose_name="Eğitim-Öğretim Yılı",
            ),
        ),
        migrations.AddField(
            model_name="secmelidersgrubu",
            name="egitim_yili",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secmeli_ders_gruplari",
                to="okul.egitimogretimyili",
                verbose_name="Eğitim-Öğretim Yılı",
            ),
        ),
        migrations.AddField(
            model_name="sinifseviyetoplamsaat",
            name="egitim_yili",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sinif_toplam_saatler",
                to="okul.egitimogretimyili",
                verbose_name="Eğitim-Öğretim Yılı",
            ),
        ),
        migrations.AlterField(
            model_name="sinifseviyetoplamsaat",
            name="sinif_seviyesi",
            field=models.IntegerField(
                choices=[
                    (9, "9. Sınıf"),
                    (10, "10. Sınıf"),
                    (11, "11. Sınıf"),
                    (12, "12. Sınıf"),
                ],
                verbose_name="Sınıf Seviyesi",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alan",
            unique_together={("egitim_yili", "sinif_seviyesi", "adi")},
        ),
        migrations.AlterUniqueTogether(
            name="ortakders",
            unique_together={("egitim_yili", "sinif_seviyesi", "ders_adi")},
        ),
        migrations.AlterUniqueTogether(
            name="secmelidersgrubu",
            unique_together={("egitim_yili", "sinif_seviyesi", "adi")},
        ),
        migrations.AlterUniqueTogether(
            name="sinifseviyetoplamsaat",
            unique_together={("egitim_yili", "sinif_seviyesi")},
        ),
    ]
