# Generated by Django 6.0.3 on 2026-06-21 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ogrenci", "0010_okulno_charfield_to_positiveinteger"),
        ("okul", "0012_add_aktif_veri_konfigurasyonu"),
        ("secmelidersler", "0013_egitim_yili_veri_damgasi"),
    ]

    operations = [
        migrations.CreateModel(
            name="OgrenciOrtalama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "a_ortalama",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Ağırlıklı Ortalama",
                    ),
                ),
                (
                    "guncelleme",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "egitim_yili",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ogrenci_ortalamalar",
                        to="okul.egitimogretimyili",
                        verbose_name="Eğitim-Öğretim Yılı",
                    ),
                ),
                (
                    "ogrenci",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ortalamalar",
                        to="ogrenci.ogrenci",
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci Ortalaması",
                "verbose_name_plural": "Öğrenci Ortalamaları",
                "ordering": ["ogrenci__okulno"],
                "unique_together": {("ogrenci", "egitim_yili")},
            },
        ),
    ]
