# Generated by Django 6.0.3 on 2026-06-21 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ogrenci", "0010_okulno_charfield_to_positiveinteger"),
        ("okul", "0012_add_aktif_veri_konfigurasyonu"),
        ("secmelidersler", "0015_ogrenci_tasdikname"),
    ]

    operations = [
        migrations.CreateModel(
            name="OgrenciSinifTekrari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Açıklama"
                    ),
                ),
                ("olusturma", models.DateTimeField(auto_now_add=True)),
                (
                    "egitim_yili",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sinif_tekrarilar",
                        to="okul.egitimogretimyili",
                        verbose_name="Eğitim-Öğretim Yılı",
                    ),
                ),
                (
                    "ogrenci",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sinif_tekrari",
                        to="ogrenci.ogrenci",
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sınıf Tekrarı",
                "verbose_name_plural": "Sınıf Tekrarları",
            },
        ),
    ]
