# Generated by Django 6.0.3 on 2026-07-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0015_drop_bildirim_gonderici_tables'),
        ('secmelidersler', '0016_ogrenci_sinif_tekrari'),
    ]

    operations = [
        migrations.AddField(
            model_name='ortakders',
            name='branslar',
            field=models.ManyToManyField(blank=True, help_text='Öğretmen ders yükü dağıtımında bu derse aynı branştaki öğretmenler önerilir. Bazı dersler (örn. GÖRSEL SANATLAR/MÜZİK) birden fazla branştan okutulabilir.', related_name='ortak_dersler', to='okul.brans', verbose_name='Branş(lar)'),
        ),
        migrations.AddField(
            model_name='secmeliders',
            name='branslar',
            field=models.ManyToManyField(blank=True, help_text='Öğretmen ders yükü dağıtımında bu derse aynı branştaki öğretmenler önerilir. Bazı dersler (örn. GÖRSEL SANATLAR/MÜZİK) birden fazla branştan okutulabilir.', related_name='secmeli_dersler', to='okul.brans', verbose_name='Branş(lar)'),
        ),
        migrations.CreateModel(
            name='DersOgretmenAtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelecek_sinif', models.IntegerField(choices=[(9, '9. Sınıf'), (10, '10. Sınıf'), (11, '11. Sınıf'), (12, '12. Sınıf')], verbose_name='Gelecek Sınıf Seviyesi')),
                ('sube_no', models.PositiveSmallIntegerField(default=1, help_text='Alan içindeki paralel şube sırası (Şube 1, Şube 2, ...).', verbose_name='Şube No')),
                ('sube', models.CharField(blank=True, max_length=2, verbose_name='Mevcut Şube Harfi')),
                ('haftalik_saat', models.PositiveSmallIntegerField(verbose_name='Haftalık Saat')),
                ('alan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ders_ogretmen_atamalari', to='secmelidersler.alan', verbose_name='Alan')),
                ('egitim_yili', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ders_ogretmen_atamalari', to='okul.egitimogretimyili', verbose_name='Eğitim-Öğretim Yılı')),
                ('ogretmen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ders_atamalari', to='okul.personel', verbose_name='Öğretmen')),
                ('ortak_ders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ogretmen_atamalari', to='secmelidersler.ortakders', verbose_name='Ortak Ders')),
                ('secmeli_ders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ogretmen_atamalari', to='secmelidersler.secmeliders', verbose_name='Seçmeli Ders')),
            ],
            options={
                'verbose_name': 'Ders Öğretmen Ataması',
                'verbose_name_plural': 'Ders Öğretmen Atamaları',
                'ordering': ['gelecek_sinif', 'alan__sira', 'sube', 'sube_no'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('ortak_ders__isnull', False), ('secmeli_ders__isnull', True)), models.Q(('ortak_ders__isnull', True), ('secmeli_ders__isnull', False)), _connector='OR'), name='dersogretmenatama_tek_ders_turu')],
                'unique_together': {('egitim_yili', 'gelecek_sinif', 'alan', 'sube_no', 'sube', 'ortak_ders'), ('egitim_yili', 'gelecek_sinif', 'alan', 'sube_no', 'sube', 'secmeli_ders')},
            },
        ),
    ]
