# Generated by Django 6.0.3 on 2026-07-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0018_alter_personel_durum'),
        ('secmelidersler', '0018_ortakdershavuzu_branslar'),
    ]

    operations = [
        migrations.AddField(
            model_name='secmelidershavuzu',
            name='branslar',
            field=models.ManyToManyField(blank=True, help_text='Öğretmen ders yükü dağıtımında bu derse aynı branştaki öğretmenler önerilir. Bazı dersler birden fazla branştan okutulabilir.', related_name='secmeli_ders_havuzu', to='okul.brans', verbose_name='Branş(lar)'),
        ),
    ]
