# Generated by Django 6.0.3 on 2026-08-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secmelidersler', '0020_tasdiknameli_ogrenci_pasif'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dersogretmenatama',
            unique_together=None,
        ),
        migrations.RemoveConstraint(
            model_name='dersogretmenatama',
            name='dersogretmenatama_tek_ders_turu',
        ),
        migrations.DeleteModel(
            name='DersOgretmenAtama',
        ),
    ]
