# Generated by Django 6.0.3 on 2026-08-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmelidersler', '0021_alter_dersogretmenatama_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alan',
            name='sinif_seviyesi',
            field=models.IntegerField(choices=[(9, '9. Sınıf'), (10, '10. Sınıf'), (11, '11. Sınıf'), (12, '12. Sınıf')], verbose_name='Sınıf Seviyesi'),
        ),
    ]
