# Generated by Django 6.0.3 on 2026-08-16 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmelidersler', '0022_alter_alan_sinif_seviyesi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlanSubeAtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subeler', models.CharField(help_text='Virgülle ayrılmış şube harfleri. Örn: A,B,C', max_length=100, verbose_name='Şubeler')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('alan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sube_atamasi', to='secmelidersler.alan', verbose_name='Alan')),
            ],
            options={
                'verbose_name': 'Alan Şube Ataması',
                'verbose_name_plural': 'Alan Şube Atamaları',
                'db_table': 'secmelidersler_alan_sube_atama',
            },
        ),
    ]
