# Generated by Django 6.0.3 on 2026-08-16 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0022_personel_ogretmenlik_alani'),
        ('secmelidersler', '0023_alansubeatama'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoneticiZorunluDersYuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saat', models.PositiveSmallIntegerField(default=0, verbose_name='Zorunlu Ders Yükü (Saat)')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('personel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zorunlu_ders_yuku', to='okul.personel', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Yönetici Zorunlu Ders Yükü',
                'verbose_name_plural': 'Yönetici Zorunlu Ders Yükleri',
                'db_table': 'secmelidersler_yonetici_zorunlu_ders_yuku',
            },
        ),
    ]
