# Generated by Django 6.0.3 on 2026-08-16 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0022_personel_ogretmenlik_alani'),
        ('secmelidersler', '0024_yoneticizorunludersyuku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormKadroArsivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Arşivlenme Tarihi')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='norm_kadro_arsivleri', to='okul.egitimogretimyili', verbose_name='Eğitim-Öğretim Yılı')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Norm Kadro Arşivi',
                'verbose_name_plural': 'Norm Kadro Arşivleri',
                'db_table': 'secmelidersler_norm_kadro_arsivi',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='NormKadroArsiviSatiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ortak_saat', models.PositiveIntegerField(default=0, verbose_name='Ortak Saat')),
                ('secmeli_saat', models.PositiveIntegerField(default=0, verbose_name='Seçmeli Saat')),
                ('toplam_saat', models.PositiveIntegerField(default=0, verbose_name='Toplam Saat')),
                ('yonetici_dusum_saat', models.PositiveIntegerField(default=0, verbose_name='Yönetici Düşümü')),
                ('norm_hesap_saati', models.PositiveIntegerField(default=0, verbose_name='Norm Hesap Saati')),
                ('norm_kadro', models.PositiveSmallIntegerField(default=0, verbose_name='Norm Kadro')),
                ('mevcut', models.PositiveSmallIntegerField(default=0, verbose_name='Mevcut')),
                ('fazla', models.PositiveSmallIntegerField(default=0, verbose_name='Fazla')),
                ('eksik', models.PositiveSmallIntegerField(default=0, verbose_name='Eksik')),
                ('arsiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satirlar', to='secmelidersler.normkadroarsivi', verbose_name='Arşiv')),
                ('brans', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='okul.brans', verbose_name='Branş')),
            ],
            options={
                'verbose_name': 'Norm Kadro Arşivi Satırı',
                'verbose_name_plural': 'Norm Kadro Arşivi Satırları',
                'db_table': 'secmelidersler_norm_kadro_arsivi_satiri',
                'ordering': ['brans__ad'],
                'unique_together': {('arsiv', 'brans')},
            },
        ),
    ]
