# Generated by Django 6.0.3 on 2026-08-16 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0022_personel_ogretmenlik_alani'),
        ('secmelidersler', '0025_normkadroarsivi_normkadroarsivisatiri'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecmeliDersBransPaylasimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subeler', models.CharField(help_text='Bu branşa ayrılan gerçek şubeler, virgülle ayrılmış. Örn: A,B', max_length=100, verbose_name='Şubeler')),
                ('alan_ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brans_paylasimlari', to='secmelidersler.alanders', verbose_name='Alan Dersi')),
                ('brans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='okul.brans', verbose_name='Branş')),
            ],
            options={
                'verbose_name': 'Seçmeli Ders Branş Paylaşımı',
                'verbose_name_plural': 'Seçmeli Ders Branş Paylaşımları',
                'db_table': 'secmelidersler_secmeli_ders_brans_paylasimi',
                'unique_together': {('alan_ders', 'brans')},
            },
        ),
    ]
