# Generated by Django 6.0.3 on 2026-08-16 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0022_personel_ogretmenlik_alani'),
        ('secmelidersler', '0026_secmelidersbranspaylasimi'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secmelidersbranspaylasimi',
            unique_together={('alan_ders', 'brans')},
        ),
        migrations.AddField(
            model_name='secmelidersbranspaylasimi',
            name='ortak_ders',
            field=models.ForeignKey(blank=True, help_text="Yalnızca BRANS_PAYLASIM_ISTISNA_ORTAK_DERSLER'de tanımlı istisna Ortak Dersler için kullanılır.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brans_paylasimlari', to='secmelidersler.ortakders', verbose_name='Ortak Ders (istisna)'),
        ),
        migrations.AlterField(
            model_name='secmelidersbranspaylasimi',
            name='alan_ders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brans_paylasimlari', to='secmelidersler.alanders', verbose_name='Alan Dersi'),
        ),
        migrations.AlterUniqueTogether(
            name='secmelidersbranspaylasimi',
            unique_together={('alan_ders', 'brans'), ('ortak_ders', 'brans')},
        ),
        migrations.AddConstraint(
            model_name='secmelidersbranspaylasimi',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('alan_ders__isnull', False), ('ortak_ders__isnull', True)), models.Q(('alan_ders__isnull', True), ('ortak_ders__isnull', False)), _connector='OR'), name='secmelidersler_brans_paylasimi_tek_kaynak'),
        ),
    ]
