# Generated by Django 6.0.3 on 2026-08-16 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmelidersler', '0027_alter_secmelidersbranspaylasimi_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecmeliDersSubeBolunmesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sube', models.CharField(max_length=2, verbose_name='Şube')),
                ('parcalar', models.CharField(help_text='Virgülle ayrılmış saat değerleri. Örn: 1,2 ya da 2,2,2', max_length=60, verbose_name='Saat Parçaları')),
                ('alan_ders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sube_bolunmeleri', to='secmelidersler.alanders', verbose_name='Alan Dersi')),
                ('ortak_ders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sube_bolunmeleri', to='secmelidersler.ortakders', verbose_name='Ortak Ders (istisna)')),
            ],
            options={
                'verbose_name': 'Seçmeli Ders Şube Bölünmesi',
                'verbose_name_plural': 'Seçmeli Ders Şube Bölünmeleri',
                'db_table': 'secmelidersler_secmeli_ders_sube_bolunmesi',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('alan_ders__isnull', False), ('ortak_ders__isnull', True)), models.Q(('alan_ders__isnull', True), ('ortak_ders__isnull', False)), _connector='OR'), name='secmelidersler_sube_bolunmesi_tek_kaynak')],
                'unique_together': {('alan_ders', 'sube'), ('ortak_ders', 'sube')},
            },
        ),
    ]
