# Generated by Django 6.0.3 on 2026-05-28 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ogrenci", "0010_okulno_charfield_to_positiveinteger"),
        ("ogrencidersleri", "0001_initial"),
        ("okul", "0012_add_aktif_veri_konfigurasyonu"),
    ]

    operations = [
        migrations.CreateModel(
            name="OgrenciMevcutDers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "haftalik_saat",
                    models.PositiveSmallIntegerField(verbose_name="Haftalık Saat"),
                ),
                (
                    "ders",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ogrenci_mevcut",
                        to="okul.dershavuzu",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "ogrenci",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mevcut_dersler",
                        to="ogrenci.ogrenci",
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci Mevcut Ders",
                "verbose_name_plural": "Öğrenci Mevcut Dersleri",
                "ordering": ["ogrenci", "ders__ders_adi"],
                "unique_together": {("ogrenci", "ders")},
            },
        ),
    ]
