# Generated by Django 6.0.3 on 2026-07-01 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0011_alter_ogrencimuaf_unique_together_and_more'),
        ('ogrencidersleri', '0002_ogrenci_mevcut_ders'),
        ('okul', '0012_add_aktif_veri_konfigurasyonu'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ogrencimevcutders',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ogrencimevcutders',
            name='egitim_yili',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='okul.egitimogretimyili', verbose_name='Eğitim-Öğretim Yılı'),
        ),
        migrations.AlterUniqueTogether(
            name='ogrencimevcutders',
            unique_together={('egitim_yili', 'ogrenci', 'ders')},
        ),
    ]
