# Generated by Django 6.0.3 on 2026-03-27 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devamsizlik", "0001_initial"),
        ("okul", "0004_add_ders_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="ogrencidevamsizlik",
            name="ders_saati_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devamsizlik",
                to="okul.derssaatleri",
                verbose_name="Ders Saati (FK)",
            ),
        ),
    ]
