# Generated by Django 6.0.3 on 2026-03-27 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devamsizlik", "0004_replace_ders_saati_field"),
        ("okul", "0004_add_ders_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ogrencidevamsizlik",
            options={
                "ordering": ["-tarih", "ders_saati__derssaati_no"],
                "verbose_name": "Öğrenci Devamsızlık",
                "verbose_name_plural": "Öğrenci Devamsızlıkları",
            },
        ),
        migrations.AlterField(
            model_name="ogrencidevamsizlik",
            name="ders_saati",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devamsizlik",
                to="okul.derssaatleri",
                verbose_name="Ders Saati",
            ),
        ),
    ]
