# Generated by Django 6.0.3 on 2026-09-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devamsizlik', '0005_alter_ordering_and_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrencidevamsizlik',
            name='arsivlendi',
            field=models.BooleanField(default=False, help_text='Sene Sonu Geçişi uygulandığında geçmiş eğitim-öğretim yılına ait devamsızlık kayıtları otomatik olarak arşivlenir; arşivlenen kayıtlar varsayılan devamsızlık listesinde görünmez (tarih filtresiyle aranabilir).', verbose_name='Arşivlendi'),
        ),
    ]
