# Generated by Django 6.0.3 on 2026-04-25 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("okul", "0012_add_aktif_veri_konfigurasyonu"),
    ]

    operations = [
        migrations.CreateModel(
            name="SorumluGun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
            ],
            options={
                "verbose_name": "Sınav Günü",
                "verbose_name_plural": "Sınav Günleri",
                "ordering": ["tarih"],
            },
        ),
        migrations.CreateModel(
            name="SorumluOturum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oturum_no",
                    models.PositiveSmallIntegerField(verbose_name="Oturum No"),
                ),
                ("saat_baslangic", models.TimeField(verbose_name="Başlangıç")),
                ("saat_bitis", models.TimeField(verbose_name="Bitiş")),
                (
                    "sinav_turu",
                    models.CharField(
                        choices=[("Yazili", "Yazılı"), ("Uygulama", "Uygulama")],
                        default="Yazili",
                        max_length=20,
                        verbose_name="Tür",
                    ),
                ),
                (
                    "gun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oturumlar",
                        to="sorumluluk.sorumlugun",
                        verbose_name="Gün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oturum",
                "verbose_name_plural": "Oturumlar",
                "ordering": ["gun__tarih", "oturum_no"],
                "unique_together": {("gun", "oturum_no")},
            },
        ),
        migrations.CreateModel(
            name="SorumluSinav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sinav_adi",
                    models.CharField(max_length=200, verbose_name="Sınav Adı"),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Açıklama"
                    ),
                ),
                (
                    "donem_turu",
                    models.CharField(
                        choices=[
                            ("EYLUL", "Eylül Dönemi"),
                            ("SUBAT", "Şubat Dönemi"),
                            ("HAZIRAN", "Haziran Dönemi"),
                        ],
                        default="HAZIRAN",
                        max_length=10,
                        verbose_name="Dönem",
                    ),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "onaylandi",
                    models.BooleanField(default=False, verbose_name="Onaylandı"),
                ),
                (
                    "onay_tarihi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Onay Tarihi"
                    ),
                ),
                (
                    "egitim_yili",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sorumluluk_sinavlari",
                        to="okul.egitimogretimyili",
                        verbose_name="Eğitim-Öğretim Yılı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sorumluluk Sınavı",
                "verbose_name_plural": "Sorumluluk Sınavları",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="SorumluOgrenci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("okulno", models.CharField(max_length=20, verbose_name="Okul No")),
                (
                    "adi_soyadi",
                    models.CharField(max_length=200, verbose_name="Adı Soyadı"),
                ),
                (
                    "sinif",
                    models.PositiveSmallIntegerField(verbose_name="Mevcut Sınıf"),
                ),
                ("sube", models.CharField(max_length=4, verbose_name="Şube")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "sinav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ogrenciler",
                        to="sorumluluk.sorumlusinav",
                        verbose_name="Sınav",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sorumlu Öğrenci",
                "verbose_name_plural": "Sorumlu Öğrenciler",
                "ordering": ["sinif", "sube", "adi_soyadi"],
                "unique_together": {("sinav", "okulno")},
            },
        ),
        migrations.AddField(
            model_name="sorumlugun",
            name="sinav",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gunler",
                to="sorumluluk.sorumlusinav",
                verbose_name="Sınav",
            ),
        ),
        migrations.CreateModel(
            name="SorumluDersHavuzu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ders_adi", models.CharField(max_length=200, verbose_name="Ders Adı")),
                (
                    "onceki_sinif",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Sınıf Seviyesi"
                    ),
                ),
                (
                    "sinav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ders_havuzu",
                        to="sorumluluk.sorumlusinav",
                        verbose_name="Sınav",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sorumlu Ders Havuzu",
                "verbose_name_plural": "Sorumlu Ders Havuzu",
                "ordering": ["onceki_sinif", "ders_adi"],
                "unique_together": {("sinav", "ders_adi", "onceki_sinif")},
            },
        ),
        migrations.CreateModel(
            name="SorumluDers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "havuz_dersi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sorumlu_ogrenciler",
                        to="sorumluluk.sorumludershavuzu",
                        verbose_name="Havuz Dersi",
                    ),
                ),
                (
                    "ogrenci",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dersler",
                        to="sorumluluk.sorumluogrenci",
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sorumlu Ders",
                "verbose_name_plural": "Sorumlu Dersler",
                "ordering": ["havuz_dersi__ders_adi"],
                "unique_together": {("ogrenci", "havuz_dersi")},
            },
        ),
        migrations.CreateModel(
            name="SorumluOturumDers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ders_adi", models.CharField(max_length=200, verbose_name="Ders Adı")),
                (
                    "oturum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dersler",
                        to="sorumluluk.sorumluoturum",
                        verbose_name="Oturum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oturum Dersi",
                "verbose_name_plural": "Oturum Dersleri",
                "unique_together": {("oturum", "ders_adi")},
            },
        ),
        migrations.CreateModel(
            name="SorumluOturmaPlani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salon",
                    models.CharField(
                        choices=[
                            ("Sorumluluk1", "Sorumluluk1"),
                            ("Sorumluluk2", "Sorumluluk2"),
                        ],
                        max_length=20,
                        verbose_name="Salon",
                    ),
                ),
                ("sira_no", models.PositiveSmallIntegerField(verbose_name="Sıra No")),
                ("okulno", models.CharField(max_length=20, verbose_name="Okul No")),
                (
                    "adi_soyadi",
                    models.CharField(max_length=200, verbose_name="Adı Soyadı"),
                ),
                (
                    "sinifsube",
                    models.CharField(max_length=10, verbose_name="Sınıf/Şube"),
                ),
                ("ders_adi", models.CharField(max_length=200, verbose_name="Ders")),
                (
                    "onceki_sinif",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Sınıf"
                    ),
                ),
                (
                    "oturum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oturma_plani",
                        to="sorumluluk.sorumluoturum",
                        verbose_name="Oturum",
                    ),
                ),
                (
                    "sinav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oturma_plani",
                        to="sorumluluk.sorumlusinav",
                        verbose_name="Sınav",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oturma Planı Kaydı",
                "verbose_name_plural": "Oturma Planı",
                "ordering": [
                    "oturum__gun__tarih",
                    "oturum__oturum_no",
                    "salon",
                    "sira_no",
                ],
                "unique_together": {("oturum", "salon", "sira_no")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="sorumlugun",
            unique_together={("sinav", "tarih")},
        ),
    ]
