# Generated by Django 6.0.3 on 2026-04-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorumluluk", "0002_refactor_takvim_flat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sorumluoturmaplani",
            name="salon",
            field=models.CharField(
                choices=[
                    ("Sorumluluk1", "Mazeret 1"),
                    ("Sorumluluk2", "Mazeret 2"),
                    ("Sorumluluk3", "Mazeret 3"),
                ],
                max_length=20,
                verbose_name="Salon",
            ),
        ),
    ]
