# Generated by Django 6.0.3 on 2026-04-26 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okul", "0012_add_aktif_veri_konfigurasyonu"),
        ("sorumluluk", "0003_add_salon3"),
    ]

    operations = [
        migrations.CreateModel(
            name="SorumluKomisyonUyesi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "takvim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="komisyon_uyesi",
                        to="sorumluluk.sorumlutakvim",
                        verbose_name="Takvim Kaydı",
                    ),
                ),
                (
                    "uye1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="okul.personel",
                        verbose_name="1. Komisyon Üyesi",
                    ),
                ),
                (
                    "uye2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="okul.personel",
                        verbose_name="2. Komisyon Üyesi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Komisyon Üyesi",
                "verbose_name_plural": "Komisyon Üyeleri",
            },
        ),
        migrations.CreateModel(
            name="SorumluGozetmen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "oturum_no",
                    models.PositiveSmallIntegerField(verbose_name="Oturum No"),
                ),
                (
                    "salon",
                    models.CharField(
                        choices=[
                            ("Sorumluluk1", "Mazeret 1"),
                            ("Sorumluluk2", "Mazeret 2"),
                            ("Sorumluluk3", "Mazeret 3"),
                        ],
                        max_length=20,
                        verbose_name="Salon",
                    ),
                ),
                (
                    "gozetmen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="okul.personel",
                        verbose_name="Gözetmen",
                    ),
                ),
                (
                    "sinav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gozetmenler",
                        to="sorumluluk.sorumlusinav",
                        verbose_name="Sınav",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gözetmen",
                "verbose_name_plural": "Gözetmenler",
                "ordering": ["tarih", "oturum_no", "salon"],
                "unique_together": {("sinav", "tarih", "oturum_no", "salon")},
            },
        ),
    ]
