# Generated by Django 6.0.3 on 2026-06-21 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okul", "0012_add_aktif_veri_konfigurasyonu"),
        ("sorumluluk", "0005_komisyon_takvimden_bagimsi"),
    ]

    operations = [
        migrations.CreateModel(
            name="OncekiGorevSayisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "komisyon",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Önceki Komisyon"
                    ),
                ),
                (
                    "gozetmen",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Önceki Gözetmen"
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Açıklama"
                    ),
                ),
                (
                    "personel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onceki_gorev_sayisi",
                        to="okul.personel",
                        verbose_name="Personel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Önceki Görev Sayısı",
                "verbose_name_plural": "Önceki Görev Sayıları",
            },
        ),
    ]
