# Generated by Django 6.0.3 on 2026-06-21 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okul", "0012_add_aktif_veri_konfigurasyonu"),
        ("sorumluluk", "0006_onceki_gorev_sayisi"),
    ]

    operations = [
        migrations.CreateModel(
            name="OncekiDonem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sinav_adi",
                    models.CharField(
                        max_length=200, verbose_name="Sınav Adı / Dönem Adı"
                    ),
                ),
                (
                    "donem_turu",
                    models.CharField(
                        choices=[
                            ("EYLUL", "Eylül Dönemi"),
                            ("SUBAT", "Şubat Dönemi"),
                            ("HAZIRAN", "Haziran Dönemi"),
                        ],
                        default="HAZIRAN",
                        max_length=10,
                        verbose_name="Dönem",
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Açıklama"
                    ),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "egitim_yili",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="okul.egitimogretimyili",
                        verbose_name="Eğitim-Öğretim Yılı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Önceki Dönem",
                "verbose_name_plural": "Önceki Dönemler",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="OncekiDonemGorev",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "komisyon",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Komisyon"
                    ),
                ),
                (
                    "gozetmen",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Gözetmen"
                    ),
                ),
                (
                    "donem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gorevler",
                        to="sorumluluk.oncekidonem",
                        verbose_name="Dönem",
                    ),
                ),
                (
                    "personel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onceki_donem_gorevler",
                        to="okul.personel",
                        verbose_name="Personel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Önceki Dönem Görevi",
                "verbose_name_plural": "Önceki Dönem Görevleri",
                "ordering": ["personel__brans", "personel__adi_soyadi"],
                "unique_together": {("donem", "personel")},
            },
        ),
        migrations.DeleteModel(
            name="OncekiGorevSayisi",
        ),
    ]
