# Generated by Django 6.0.3 on 2026-07-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorumluluk', '0007_oncekidonem_replace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oncekidonemgorev',
            options={'ordering': ['personel__brans__ad', 'personel__adi_soyadi'], 'verbose_name': 'Önceki Dönem Görevi', 'verbose_name_plural': 'Önceki Dönem Görevleri'},
        ),
    ]
