# Generated by Django 6.0.3 on 2026-07-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0015_drop_bildirim_gonderici_tables'),
        ('sorumluluk', '0008_alter_oncekidonemgorev_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SorumluGorevMuafPersonel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(blank=True, max_length=300, verbose_name='Açıklama')),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('personel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sorumluluk_gorev_muafiyeti', to='okul.personel', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Görev Muafiyeti',
                'verbose_name_plural': 'Görev Muafiyetleri',
                'ordering': ['personel__adi_soyadi'],
            },
        ),
    ]
