# Generated by Django 6.0.3 on 2026-07-14 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorumluluk', '0009_sorumlugorevmuafpersonel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SorumluDersKatalogu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_adi', models.CharField(max_length=200, verbose_name='Ders Adı')),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ders_katalogu', to='sorumluluk.sorumlusinav', verbose_name='Sınav')),
            ],
            options={
                'verbose_name': 'Ders Kataloğu',
                'verbose_name_plural': 'Ders Kataloğu',
                'ordering': ['ders_adi'],
                'unique_together': {('sinav', 'ders_adi')},
            },
        ),
    ]
