# Generated by Django 6.0.3 on 2026-07-14 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0015_drop_bildirim_gonderici_tables'),
        ('sorumluluk', '0010_sorumluderskatalogu'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorumludershavuzu',
            name='brans',
            field=models.ForeignKey(blank=True, help_text="Haftalık Ders Programı'ndaki öğretmen atamalarından otomatik belirlenir.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorumluluk_ders_havuzu', to='okul.brans', verbose_name='Branş'),
        ),
    ]
