# Generated by Django 6.0.3 on 2026-07-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0015_drop_bildirim_gonderici_tables'),
        ('sorumluluk', '0011_sorumludershavuzu_brans'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorumluderskatalogu',
            name='branslar',
            field=models.ManyToManyField(blank=True, help_text="Haftalık Ders Programı'ndaki öğretmen atamalarından otomatik önerilir (sadece eklenir); elle ekleyip çıkarabilirsiniz. Bazı dersler (örn. GÖRSEL SANATLAR/MÜZİK) birden fazla branştan öğretmen tarafından okutulabilir.", related_name='sorumluluk_ders_katalogu', to='okul.brans', verbose_name='Branşlar'),
        ),
    ]
