# Generated by Django 6.0.3 on 2026-07-14 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0015_drop_bildirim_gonderici_tables'),
        ('sorumluluk', '0012_sorumluderskatalogu_branslar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorumluderskatalogu',
            name='branslar',
            field=models.ManyToManyField(blank=True, help_text="Haftalık Ders Programı'ndaki öğretmen atamalarından tespit edilen yeni branş eşleşmeleri, doğrudan eklenmeden önce onayınıza sunulur (bkz. Branş Önerileri). Buradan elle de ekleyip çıkarabilirsiniz. Bazı dersler (örn. GÖRSEL SANATLAR/MÜZİK) birden fazla branştan öğretmen tarafından okutulabilir.", related_name='sorumluluk_ders_katalogu', to='okul.brans', verbose_name='Branşlar'),
        ),
        migrations.CreateModel(
            name='SorumluDersKatalogBransOneri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('brans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='okul.brans', verbose_name='Önerilen Branş')),
                ('katalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brans_onerileri', to='sorumluluk.sorumluderskatalogu', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Branş Önerisi',
                'verbose_name_plural': 'Branş Önerileri',
                'ordering': ['katalog__ders_adi'],
                'unique_together': {('katalog', 'brans')},
            },
        ),
    ]
