# Generated by Django 6.0.3 on 2026-07-14 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0015_drop_bildirim_gonderici_tables'),
        ('sorumluluk', '0013_alter_sorumluderskatalogu_branslar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorumluderskatalogu',
            name='okul_dersi',
            field=models.ForeignKey(blank=True, help_text="Ders adı, Okul Ders Havuzu'ndaki bir kayıtla eşleşiyorsa otomatik bağlanır. Nakil öğrenci nedeniyle Okul Ders Havuzu'nda karşılığı olmayan dersler boş kalabilir (bkz. Okul Ders Havuzu Önerileri).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorumluluk_ders_katalogu', to='okul.dershavuzu', verbose_name='Okul Ders Havuzu Kaydı'),
        ),
        migrations.CreateModel(
            name='SorumluDersKatalogOkulDersOnerisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('katalog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='okul_dersi_onerisi', to='sorumluluk.sorumluderskatalogu', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Okul Ders Havuzu Önerisi',
                'verbose_name_plural': 'Okul Ders Havuzu Önerileri',
                'ordering': ['katalog__ders_adi'],
            },
        ),
    ]
