# Generated by Django 6.0.3 on 2026-07-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorumluluk', '0014_sorumluderskatalogu_okul_dersi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorumlusinav',
            name='arsivlendi',
            field=models.BooleanField(default=False, verbose_name='Arşivlendi'),
        ),
        migrations.AddField(
            model_name='sorumlusinav',
            name='arsivlenme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arşivlenme Tarihi'),
        ),
    ]
