# Generated by Django 6.0.3 on 2026-07-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0018_alter_personel_durum'),
        ('secmelidersler', '0019_secmelidershavuzu_branslar'),
        ('sorumluluk', '0015_sorumlusinav_arsivlendi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorumluderskatalogu',
            name='ortak_ders',
            field=models.ForeignKey(blank=True, help_text='Ders adı otomatik eşleşmediğinde elle bağlanabilir; branşlar buradan senkronize edilir. Seçmeli Ders ile birlikte seçilemez.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='secmelidersler.ortakdershavuzu', verbose_name='Eşleşen Ortak Ders (Havuz)'),
        ),
        migrations.AddField(
            model_name='sorumluderskatalogu',
            name='secmeli_ders',
            field=models.ForeignKey(blank=True, help_text='Ders adı otomatik eşleşmediğinde elle bağlanabilir; branşlar buradan senkronize edilir. Ortak Ders ile birlikte seçilemez.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='secmelidersler.secmelidershavuzu', verbose_name='Eşleşen Seçmeli Ders (Havuz)'),
        ),
        migrations.AlterField(
            model_name='sorumluderskatalogu',
            name='branslar',
            field=models.ManyToManyField(blank=True, help_text="secmelidersler'deki (Ortak/Seçmeli Ders Havuzu) aynı adlı kayıtların branşlarından tespit edilen yeni eşleşmeler, doğrudan eklenmeden önce onayınıza sunulur (bkz. Branş Önerileri). Buradan elle de ekleyip çıkarabilirsiniz. Bazı dersler (örn. GÖRSEL SANATLAR/MÜZİK) birden fazla branştan öğretmen tarafından okutulabilir.", related_name='sorumluluk_ders_katalogu', to='okul.brans', verbose_name='Branşlar'),
        ),
        migrations.AddConstraint(
            model_name='sorumluderskatalogu',
            constraint=models.CheckConstraint(condition=models.Q(('ortak_ders__isnull', False), ('secmeli_ders__isnull', False), _negated=True), name='sorumluderskatalogu_tek_secmeli_ders_turu'),
        ),
    ]
