# Generated by Django 6.0.3 on 2026-09-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorumluluk', '0016_sorumluderskatalogu_ortak_ders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SorumlulukSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.PositiveSmallIntegerField(unique=True, verbose_name='Sıra (Salon No)')),
                ('ad', models.CharField(max_length=50, verbose_name='Salon Adı')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salonlar',
                'ordering': ['sira'],
            },
        ),
        migrations.AlterField(
            model_name='sorumlugozetmen',
            name='salon',
            field=models.CharField(max_length=20, verbose_name='Salon'),
        ),
        migrations.AlterField(
            model_name='sorumluoturmaplani',
            name='salon',
            field=models.CharField(max_length=20, verbose_name='Salon'),
        ),
    ]
