# Generated by Django 6.0.3 on 2026-09-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorumluluk', '0019_gecmis_gecisleri_arsivle'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncekidonem',
            name='arsivlendi',
            field=models.BooleanField(default=False, help_text='Sene Sonu Geçişi uygulandığında bu döneme ait eğitim-öğretim yılı sona erdiğinde otomatik olarak arşivlenir; arşivlenen dönemin görev sayıları (bkz. OncekiDonemGorev) adalet puanlaması kümülatiflerine artık dahil edilmez — bkz. sorumluluk/services/gorevlendirme_oneri.py, rapor_ozet.py.', verbose_name='Arşivlendi'),
        ),
    ]
