# Generated by Django 6.0.3 on 2026-03-15 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nobet", "0010_nobetpersonel_user"),
        ("ogrenci", "0003_ogrencidevamsizlik"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gorusme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "tur",
                    models.CharField(
                        choices=[
                            ("bireysel", "Bireysel Öğrenci"),
                            ("veli", "Veli Görüşmesi"),
                            ("grup", "Grup Görüşmesi"),
                            ("ogretmen", "Öğretmen Görüşmesi"),
                            ("diger", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Görüşme Türü",
                    ),
                ),
                ("konu", models.CharField(max_length=300, verbose_name="Konu")),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "sonuc",
                    models.TextField(blank=True, verbose_name="Alınan Önlem / Sonuç"),
                ),
                (
                    "takip_tarihi",
                    models.DateField(blank=True, null=True, verbose_name="Takip Tarihi"),
                ),
                (
                    "gizli",
                    models.BooleanField(default=False, verbose_name="Gizli Kayıt"),
                ),
                ("olusturma_zamani", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_zamani", models.DateTimeField(auto_now=True)),
                (
                    "ogrenci",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gorusmeler",
                        to="ogrenci.ogrenci",
                        verbose_name="Öğrenci",
                    ),
                ),
                (
                    "rehber",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gorusmeler",
                        to="nobet.nobetpersonel",
                        verbose_name="Rehber Öğretmen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Görüşme",
                "verbose_name_plural": "Görüşmeler",
                "db_table": "rehberlik_gorusme",
                "ordering": ["-tarih", "-olusturma_zamani"],
            },
        ),
    ]
