# Generated by Django 6.0.3 on 2026-03-15 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nobet", "0010_nobetpersonel_user"),
        ("ogrenci", "0003_ogrencidevamsizlik"),
        ("rehberlik", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gorusme",
            name="gorusulen_ogretmen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gorusulen_gorusmeler",
                to="nobet.nobetpersonel",
                verbose_name="Görüşülen Öğretmen",
            ),
        ),
        migrations.AddField(
            model_name="gorusme",
            name="grup_ogrencileri",
            field=models.ManyToManyField(
                blank=True,
                related_name="grup_gorusmeleri",
                to="ogrenci.ogrenci",
                verbose_name="Grup Öğrencileri",
            ),
        ),
        migrations.AddField(
            model_name="gorusme",
            name="veli_adi",
            field=models.CharField(blank=True, max_length=200, verbose_name="Veli Adı Soyadı"),
        ),
        migrations.AddField(
            model_name="gorusme",
            name="veli_telefon",
            field=models.CharField(blank=True, max_length=30, verbose_name="Veli Telefonu"),
        ),
    ]
