# Generated by Django 6.0.3 on 2026-03-15 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nobet", "0010_nobetpersonel_user"),
        ("ogrenci", "0003_ogrencidevamsizlik"),
        ("rehberlik", "0002_gorusme_tur_alanlari"),
    ]

    operations = [
        migrations.CreateModel(
            name="OgrenciCagri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "ders_saati",
                    models.IntegerField(blank=True, null=True, verbose_name="Ders Saati"),
                ),
                (
                    "ders_adi",
                    models.CharField(blank=True, max_length=100, verbose_name="Ders Adı"),
                ),
                (
                    "ogretmen_adi",
                    models.CharField(blank=True, max_length=100, verbose_name="Dersin Öğretmeni"),
                ),
                (
                    "cagri_metni",
                    models.TextField(blank=True, verbose_name="Çağrı Metni"),
                ),
                ("olusturma_zamani", models.DateTimeField(auto_now_add=True)),
                (
                    "ogrenci",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cagrilar",
                        to="ogrenci.ogrenci",
                        verbose_name="Öğrenci",
                    ),
                ),
                (
                    "rehber",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cagrilar",
                        to="nobet.nobetpersonel",
                        verbose_name="Rehber Öğretmen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci Çağrısı",
                "verbose_name_plural": "Öğrenci Çağrıları",
                "db_table": "rehberlik_ogrenci_cagri",
                "ordering": ["-tarih", "ders_saati"],
            },
        ),
    ]
