# Generated by Django 6.0.3 on 2026-09-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personeldevamsizlik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devamsizlik',
            name='arsivlendi',
            field=models.BooleanField(default=False, help_text='Sene Sonu Geçişi uygulandığında geçmiş eğitim-öğretim yılına ait devamsızlık kayıtları otomatik olarak arşivlenir; arşivlenen kayıtlar güncel devamsızlık listesinde/ders doldurma istatistiklerinde görünmez.', verbose_name='Arşivlendi'),
        ),
    ]
