# Generated by Django 6.0.3 on 2026-03-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DersProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("giris_saat", models.CharField(max_length=10)),
                ("cikis_saat", models.CharField(max_length=10)),
                ("gun", models.CharField(max_length=15)),
                ("ders_adi", models.CharField(max_length=200)),
                ("ders_ogretmeni", models.CharField(max_length=200)),
                ("sinif", models.IntegerField()),
                ("sube", models.CharField(max_length=5)),
                ("subeadi", models.CharField(max_length=20)),
                ("ders_saati", models.IntegerField(blank=True, null=True)),
                ("ders_saati_adi", models.CharField(max_length=20)),
                ("uygulama_tarihi", models.DateField()),
            ],
            options={
                "ordering": ["sinif", "sube", "ders_saati"],
            },
        ),
        migrations.CreateModel(
            name="DersSaati",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ders_adi", models.CharField(max_length=200)),
                ("sinif", models.IntegerField()),
                ("subeler", models.CharField(max_length=500)),
                ("haftalik_saat", models.FloatField()),
            ],
            options={
                "ordering": ["sinif", "ders_adi"],
            },
        ),
        migrations.CreateModel(
            name="Ogrenci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("okulno", models.CharField(max_length=20)),
                ("adi", models.CharField(max_length=100)),
                ("soyadi", models.CharField(max_length=100)),
                ("cinsiyet", models.CharField(blank=True, max_length=10)),
                ("sinifsube", models.CharField(max_length=10)),
                ("sube", models.CharField(max_length=5)),
                ("sinif", models.IntegerField()),
            ],
            options={
                "ordering": ["sinif", "sube", "soyadi", "adi"],
            },
        ),
        migrations.CreateModel(
            name="OturmaPlani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField()),
                ("saat", models.CharField(max_length=10)),
                ("oturum", models.IntegerField()),
                ("salon", models.CharField(max_length=50)),
                ("sira_no", models.IntegerField()),
                ("okulno", models.CharField(max_length=20)),
                ("sinifsube", models.CharField(max_length=10)),
                ("adi_soyadi", models.CharField(max_length=200)),
                ("ders_adi", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["tarih", "saat", "salon", "sira_no"],
            },
        ),
        migrations.CreateModel(
            name="SubeDers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ders", models.CharField(max_length=200)),
                ("seviye", models.IntegerField()),
                ("sube", models.CharField(max_length=10)),
            ],
            options={
                "ordering": ["seviye", "sube", "ders"],
            },
        ),
        migrations.CreateModel(
            name="Takvim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField()),
                ("saat", models.CharField(max_length=10)),
                ("oturum", models.IntegerField()),
                ("ders", models.CharField(max_length=200)),
                ("subeler", models.TextField()),
            ],
            options={
                "ordering": ["tarih", "saat", "ders"],
            },
        ),
    ]
