# Generated by Django 6.0.3 on 2026-03-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SinavBilgisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("egitim_ogretim_yili", models.CharField(max_length=20)),
                (
                    "donem",
                    models.CharField(
                        choices=[("1. Donem", "1. Dönem"), ("2. Donem", "2. Dönem")],
                        max_length=20,
                    ),
                ),
                (
                    "sinav_adi",
                    models.CharField(
                        choices=[
                            ("1. Ortak Sinav", "1. Ortak Sınav"),
                            ("2. Ortak Sinav", "2. Ortak Sınav"),
                        ],
                        max_length=100,
                    ),
                ),
                ("sinav_baslangic_tarihi", models.DateField()),
                ("eokul_veri_tarihi", models.DateField()),
                ("aktif", models.BooleanField(default=False)),
                ("olusturulma_zamani", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-olusturulma_zamani"],
            },
        ),
    ]
