# Generated by Django 6.0.3 on 2026-03-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0002_sinavbilgisi"),
    ]

    operations = [
        migrations.CreateModel(
            name="CiftOturumluDers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ders_adi", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ["ders_adi"],
            },
        ),
        migrations.CreateModel(
            name="SinavYapilmayacakDers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ders_adi", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ["ders_adi"],
            },
        ),
    ]
