# Generated by Django 6.0.3 on 2026-03-20 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0003_ciftoturumluders_sinavyapilmayacakders"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciftoturumluders",
            name="sinav",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cift_oturumlu_dersler",
                to="sinav.sinavbilgisi",
            ),
        ),
        migrations.AddField(
            model_name="sinavyapilmayacakders",
            name="sinav",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="yapilmayacak_dersler",
                to="sinav.sinavbilgisi",
            ),
        ),
        migrations.AlterField(
            model_name="ciftoturumluders",
            name="ders_adi",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="sinavyapilmayacakders",
            name="ders_adi",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="ciftoturumluders",
            unique_together={("sinav", "ders_adi")},
        ),
        migrations.AlterUniqueTogether(
            name="sinavyapilmayacakders",
            unique_together={("sinav", "ders_adi")},
        ),
    ]
