# Generated by Django 6.0.3 on 2026-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0007_seviyecatismagrubu"),
    ]

    operations = [
        migrations.CreateModel(
            name="SinifSube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sinif", models.IntegerField()),
                ("sube", models.CharField(max_length=5)),
                ("sinifsube", models.CharField(editable=False, max_length=10)),
                ("salon", models.CharField(editable=False, max_length=20)),
            ],
            options={
                "ordering": ["sinif", "sube"],
                "unique_together": {("sinif", "sube")},
            },
        ),
    ]
