# Generated by Django 6.0.3 on 2026-03-20 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0008_sinifsube"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dersprogram",
            options={
                "ordering": ["sinif_sube__sinif", "sinif_sube__sube", "ders_saati"]
            },
        ),
        migrations.AlterModelOptions(
            name="ogrenci",
            options={
                "ordering": ["sinif_sube__sinif", "sinif_sube__sube", "soyadi", "adi"]
            },
        ),
        migrations.RemoveField(
            model_name="dersprogram",
            name="sinif",
        ),
        migrations.RemoveField(
            model_name="dersprogram",
            name="sube",
        ),
        migrations.RemoveField(
            model_name="dersprogram",
            name="subeadi",
        ),
        migrations.RemoveField(
            model_name="ogrenci",
            name="sinif",
        ),
        migrations.RemoveField(
            model_name="ogrenci",
            name="sinifsube",
        ),
        migrations.RemoveField(
            model_name="ogrenci",
            name="sube",
        ),
        migrations.AddField(
            model_name="dersprogram",
            name="sinif_sube",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ders_programlari",
                to="sinav.sinifsube",
            ),
        ),
        migrations.AddField(
            model_name="ogrenci",
            name="sinif_sube",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ogrenciler",
                to="sinav.sinifsube",
            ),
        ),
    ]
