# Generated by Django 6.0.3 on 2026-03-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0009_alter_dersprogram_options_alter_ogrenci_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DersHavuzu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ders_adi", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ["ders_adi"],
            },
        ),
        migrations.RemoveField(
            model_name="dersprogram",
            name="ders_adi",
        ),
        migrations.AddField(
            model_name="dersprogram",
            name="ders",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ders_programlari",
                to="sinav.dershavuzu",
            ),
        ),
    ]
