# Generated by Django 6.0.3 on 2026-03-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0010_dershavuzu_remove_dersprogram_ders_adi_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OkulBilgileri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "okul_adi",
                    models.CharField(
                        default="Abdurrahim Karakoç Anadolu Lisesi",
                        max_length=200,
                        verbose_name="Okul Adı",
                    ),
                ),
                (
                    "okul_kodu",
                    models.CharField(
                        default="759725", max_length=20, verbose_name="Okul Kodu"
                    ),
                ),
                (
                    "okul_muduru",
                    models.CharField(
                        default="Neriman Sargın KOÇAK",
                        max_length=200,
                        verbose_name="Okul Müdürü",
                    ),
                ),
            ],
            options={
                "verbose_name": "Okul Bilgileri",
                "verbose_name_plural": "Okul Bilgileri",
            },
        ),
    ]
