# Generated by Django 6.0.3 on 2026-03-20 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0011_okulbilgileri"),
    ]

    operations = [
        migrations.AddField(
            model_name="sinavbilgisi",
            name="kurum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sinavlar",
                to="sinav.okulbilgileri",
                verbose_name="Kurum",
            ),
        ),
    ]
