# Generated by Django 6.0.3 on 2026-03-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0015_algoritmaparametreleri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="derssaati",
            name="ders_adi",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ders_saati",
                to="sinav.dershavuzu",
            ),
        ),
        migrations.AlterField(
            model_name="subeders",
            name="ders",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sube_dersler",
                to="sinav.dershavuzu",
            ),
        ),
        migrations.AlterField(
            model_name="subeders",
            name="sube",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sube_dersler",
                to="sinav.sinifsube",
            ),
        ),
        migrations.AlterField(
            model_name="takvim",
            name="ders",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="takvimler",
                to="sinav.dershavuzu",
            ),
        ),
    ]
