# Generated by Django 6.0.3 on 2026-03-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0016_fk_ders_sube_takvim"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subeders",
            name="sinav",
        ),
    ]
