# Generated by Django 6.0.3 on 2026-03-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0017_remove_sinav_from_subeders"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subeders",
            unique_together={("ders", "seviye", "sube")},
        ),
    ]
