# Generated by Django 6.0.3 on 2026-03-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0018_subeders_unique_together"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DersSaati",
        ),
    ]
