# Generated by Django 6.0.3 on 2026-03-20 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0019_remove_derssaati"),
    ]

    operations = [
        migrations.AddField(
            model_name="dersprogram",
            name="sinav",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ders_programlari",
                to="sinav.sinavbilgisi",
            ),
        ),
        migrations.AddField(
            model_name="ogrenci",
            name="sinav",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ogrenciler",
                to="sinav.sinavbilgisi",
            ),
        ),
    ]
