# Generated by Django 6.0.3 on 2026-03-20 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0020_add_sinav_fk_to_dersprogram_and_ogrenci"),
    ]

    operations = [
        migrations.AddField(
            model_name="disveri",
            name="sinav",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dis_veriler",
                to="sinav.sinavbilgisi",
                verbose_name="Sınav",
            ),
        ),
    ]
