# Generated by Django 6.0.3 on 2026-03-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0021_add_sinav_fk_to_disveri"),
    ]

    operations = [
        migrations.AddField(
            model_name="disveri",
            name="dosya",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dis_veri/",
                verbose_name="Excel Dosyası",
            ),
        ),
    ]
