# Generated by Django 6.0.3 on 2026-03-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0022_add_dosya_to_disveri"),
    ]

    operations = [
        migrations.AddField(
            model_name="takvim",
            name="ders_adi",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
