# Generated by Django 6.0.3 on 2026-03-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0023_add_ders_adi_to_takvim"),
    ]

    operations = [
        migrations.CreateModel(
            name="TakvimUretim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uretim_tarihi", models.DateTimeField(auto_now_add=True)),
                ("log_metni", models.TextField(blank=True, default="")),
                (
                    "sinav",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="takvim_uretimler",
                        to="sinav.sinavbilgisi",
                    ),
                ),
            ],
            options={
                "ordering": ["-uretim_tarihi"],
            },
        ),
    ]
