# Generated by Django 6.0.3 on 2026-03-21 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0024_takvim_uretim"),
    ]

    operations = [
        migrations.CreateModel(
            name="AyniSlotEsleme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ders1", models.CharField(max_length=150)),
                ("ders2", models.CharField(max_length=150)),
                (
                    "sinav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ayni_slot_eslemeler",
                        to="sinav.sinavbilgisi",
                    ),
                ),
            ],
            options={
                "ordering": ["ders1", "ders2"],
            },
        ),
    ]
