# Generated by Django 6.0.3 on 2026-03-21 11:10

import django.db.models.deletion
from django.db import migrations, models


def migrate_to_json(apps, schema_editor):
    SinavBilgisi = apps.get_model("sinav", "SinavBilgisi")
    SinavYapilmayacakDers = apps.get_model("sinav", "SinavYapilmayacakDers")
    CiftOturumluDers = apps.get_model("sinav", "CiftOturumluDers")
    SabitSinav = apps.get_model("sinav", "SabitSinav")
    SeviyeCatismaGrubu = apps.get_model("sinav", "SeviyeCatismaGrubu")
    AyniSlotEsleme = apps.get_model("sinav", "AyniSlotEsleme")
    DersAyarlariJSON = apps.get_model("sinav", "DersAyarlariJSON")

    for sinav in SinavBilgisi.objects.all():
        veri = {}

        yapilmayacak = list(
            SinavYapilmayacakDers.objects.filter(sinav=sinav).values_list("ders_adi", flat=True)
        )
        if yapilmayacak:
            veri["yapilmayacak"] = sorted(yapilmayacak)

        cift = list(
            CiftOturumluDers.objects.filter(sinav=sinav).values_list("ders_adi", flat=True)
        )
        if cift:
            veri["cift_oturumlu"] = sorted(cift)

        sabit = [
            {
                "ders_adi": ss.ders_adi,
                "tarih": str(ss.tarih),
                "saat": ss.saat,
                "seviyeler": [int(s) for s in ss.seviyeler.split(",") if s.strip().isdigit()],
            }
            for ss in SabitSinav.objects.filter(sinav=sinav).order_by("tarih", "saat")
        ]
        if sabit:
            veri["sabit_sinavlar"] = sabit

        catisma = [
            {
                "grup_adi": g.grup_adi,
                "dersler": [d.strip() for d in g.dersler.split(",") if d.strip()],
            }
            for g in SeviyeCatismaGrubu.objects.filter(sinav=sinav)
        ]
        if catisma:
            veri["catisma_gruplari"] = catisma

        esleme = [
            {"ders1": e.ders1, "ders2": e.ders2}
            for e in AyniSlotEsleme.objects.filter(sinav=sinav)
        ]
        if esleme:
            veri["ayni_slot_esleme"] = esleme

        if veri:
            DersAyarlariJSON.objects.create(sinav=sinav, veri=veri)


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0025_ayni_slot_esleme"),
    ]

    operations = [
        # 1. Önce yeni modeli oluştur
        migrations.CreateModel(
            name="DersAyarlariJSON",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("veri", models.JSONField(blank=True, default=dict)),
                (
                    "sinav",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ders_ayarlari_json",
                        to="sinav.sinavbilgisi",
                    ),
                ),
            ],
        ),
        # 2. Veriyi yeni modele kopyala (eski modeller henüz yerinde)
        migrations.RunPython(migrate_to_json, migrations.RunPython.noop),
        # 3. Eski modelleri temizle
        migrations.AlterUniqueTogether(
            name="ciftoturumluders",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="ciftoturumluders",
            name="sinav",
        ),
        migrations.AlterUniqueTogether(
            name="sabitsinav",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="sabitsinav",
            name="sinav",
        ),
        migrations.RemoveField(
            model_name="seviyecatismagrubu",
            name="sinav",
        ),
        migrations.AlterUniqueTogether(
            name="sinavyapilmayacakders",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="sinavyapilmayacakders",
            name="sinav",
        ),
        migrations.DeleteModel(
            name="AyniSlotEsleme",
        ),
        migrations.DeleteModel(
            name="CiftOturumluDers",
        ),
        migrations.DeleteModel(
            name="SabitSinav",
        ),
        migrations.DeleteModel(
            name="SeviyeCatismaGrubu",
        ),
        migrations.DeleteModel(
            name="SinavYapilmayacakDers",
        ),
    ]
