# Generated by Django 6.0.3 on 2026-03-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0026_ders_ayarlari_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="takvimuretim",
            name="aktif",
            field=models.BooleanField(
                default=False, verbose_name="PDF Raporunda Kullan"
            ),
        ),
    ]
