# Generated by Django 6.0.3 on 2026-03-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0027_takvim_uretim_aktif"),
    ]

    operations = [
        migrations.AddField(
            model_name="takvim",
            name="uretim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="takvimler_uretim",
                to="sinav.takvimuretim",
            ),
        ),
    ]
