# Generated by Django 6.0.3 on 2026-03-21 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0031_takvimuretim_degisiklik_logu"),
    ]

    operations = [
        migrations.CreateModel(
            name="OturmaUretim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField()),
                ("saat", models.CharField(max_length=10)),
                ("oturum", models.IntegerField()),
                ("uretim_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "takvim_uretim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oturma_uretimler",
                        to="sinav.takvimuretim",
                    ),
                ),
            ],
            options={
                "ordering": ["-uretim_tarihi"],
                "unique_together": {("takvim_uretim", "tarih", "saat", "oturum")},
            },
        ),
    ]
