# Generated by Django 6.0.3 on 2026-03-22 14:41

import django.db.models.deletion
from django.db import migrations, models


def temizle_sinav_fk_verileri(apps, schema_editor):
    """
    sinav.SinifSube FK'ları nobet.SinifSube'ye taşınmadan önce
    referans içeren SubeDers, DersProgram ve Ogrenci kayıtlarını temizler.
    Bu veriler e-Okul'dan yeniden aktarılacaktır.
    """
    SubeDers = apps.get_model("sinav", "SubeDers")
    DersProgram = apps.get_model("sinav", "DersProgram")
    Ogrenci = apps.get_model("sinav", "Ogrenci")
    SubeDers.objects.all().delete()
    DersProgram.objects.all().delete()
    Ogrenci.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("nobet", "0017_okul_donem_egitim_yili_fk"),
        ("sinav", "0032_oturmauretim"),
    ]

    operations = [
        migrations.RunPython(temizle_sinav_fk_verileri, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="sinavbilgisi",
            name="kurum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sinavlar",
                to="nobet.okulbilgi",
                verbose_name="Kurum",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sinifsube",
            unique_together=None,
        ),
        migrations.AlterField(
            model_name="subeders",
            name="sube",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sinav_sube_dersler",
                to="nobet.sinifsube",
            ),
        ),
        migrations.AlterField(
            model_name="ogrenci",
            name="sinif_sube",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sinav_ogrenciler",
                to="nobet.sinifsube",
            ),
        ),
        migrations.AlterField(
            model_name="dersprogram",
            name="sinif_sube",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sinav_ders_programlari",
                to="nobet.sinifsube",
            ),
        ),
        migrations.AddField(
            model_name="sinavbilgisi",
            name="donem_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sinavlar",
                to="nobet.okuldonem",
                verbose_name="Dönem (Bağlantı)",
            ),
        ),
        migrations.AddField(
            model_name="sinavbilgisi",
            name="egitim_yili_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sinavlar",
                to="nobet.egitimogretimyili",
                verbose_name="Eğitim-Öğretim Yılı (Bağlantı)",
            ),
        ),
        migrations.AlterField(
            model_name="sinavbilgisi",
            name="donem",
            field=models.CharField(
                choices=[("1. Donem", "1. Dönem"), ("2. Donem", "2. Dönem")],
                max_length=20,
                verbose_name="Dönem",
            ),
        ),
        migrations.AlterField(
            model_name="sinavbilgisi",
            name="egitim_ogretim_yili",
            field=models.CharField(max_length=20, verbose_name="Eğitim-Öğretim Yılı"),
        ),
        migrations.AlterField(
            model_name="sinavbilgisi",
            name="eokul_veri_tarihi",
            field=models.DateField(verbose_name="e-Okul Veri Tarihi"),
        ),
        migrations.AlterField(
            model_name="sinavbilgisi",
            name="sinav_adi",
            field=models.CharField(
                choices=[
                    ("1. Ortak Sinav", "1. Ortak Sınav"),
                    ("2. Ortak Sinav", "2. Ortak Sınav"),
                ],
                max_length=100,
                verbose_name="Sınav Adı",
            ),
        ),
        migrations.AlterField(
            model_name="sinavbilgisi",
            name="sinav_baslangic_tarihi",
            field=models.DateField(verbose_name="Sınav Başlangıç Tarihi"),
        ),
        migrations.DeleteModel(
            name="OkulBilgileri",
        ),
        migrations.DeleteModel(
            name="SinifSube",
        ),
    ]
