# Generated by Django 6.0.3 on 2026-03-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0033_sinav_nobet_fk_entegrasyon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ogrenci",
            name="sinav",
        ),
        migrations.RemoveField(
            model_name="ogrenci",
            name="sinif_sube",
        ),
        migrations.DeleteModel(
            name="DersProgram",
        ),
        migrations.DeleteModel(
            name="Ogrenci",
        ),
    ]
