# Generated by Django 6.0.3 on 2026-03-24 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0035_takvimuretim_onizleme_verisi"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SinavSalonYoklama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField()),
                ("saat", models.CharField(max_length=10)),
                ("salon", models.CharField(max_length=50)),
                ("okulno", models.CharField(max_length=20)),
                ("adi_soyadi", models.CharField(max_length=200)),
                ("sinifsube", models.CharField(max_length=10)),
                ("sira_no", models.IntegerField()),
                (
                    "durum",
                    models.CharField(
                        choices=[("mevcut", "Mevcut"), ("yok", "Yok"), ("gec", "Geç")],
                        default="mevcut",
                        max_length=10,
                    ),
                ),
                ("kayit_zamani", models.DateTimeField(auto_now=True)),
                (
                    "kaydeden",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uretim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salon_yoklamalar",
                        to="sinav.takvimuretim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sınav Salon Yoklama",
                "verbose_name_plural": "Sınav Salon Yoklamaları",
                "ordering": ["tarih", "saat", "salon", "sira_no"],
                "unique_together": {("uretim", "tarih", "saat", "salon", "okulno")},
            },
        ),
    ]
