# Generated by Django 6.0.3 on 2026-03-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0036_sinav_salon_yoklama"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="takvim",
            name="ders_adi",
        ),
    ]
