# Generated by Django 6.0.3 on 2026-03-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0037_remove_takvim_ders_adi"),
    ]

    operations = [
        migrations.CreateModel(
            name="DersSaatleri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "derssaati_no",
                    models.PositiveIntegerField(unique=True, verbose_name="Ders No"),
                ),
                (
                    "derssaati_baslangic",
                    models.TimeField(verbose_name="Ders Başlangıç"),
                ),
                ("derssaati_bitis", models.TimeField(verbose_name="Ders Bitiş")),
            ],
            options={
                "verbose_name": "Ders Saati",
                "verbose_name_plural": "Ders Saatleri",
                "ordering": ["derssaati_no"],
            },
        ),
    ]
