# Generated by Django 6.0.3 on 2026-03-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0039_rename_derssaatleri_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="takvim",
            name="ders_saati",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="takvimler",
                to="sinav.derssaatleri",
                verbose_name="Ders Saati",
            ),
        ),
    ]
