# Generated by Django 6.0.3 on 2026-03-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0046_add_oturmaplani_gozetmen_salon_sube"),
    ]

    operations = [
        migrations.AddField(
            model_name="takvim",
            name="sinav_turu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Normal"),
                    ("Yazili", "Yazılı"),
                    ("Uygulama", "Uygulama"),
                ],
                default="",
                max_length=20,
                verbose_name="Sınav Türü",
            ),
        ),
    ]
