# Generated by Django 6.0.3 on 2026-04-13 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okul", "0011_add_dershavuzu_sinav_alanlari"),
        ("sinav", "0049_remove_oturmaplani_gozetmen"),
    ]

    operations = [
        migrations.CreateModel(
            name="MazeretGun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
            ],
            options={
                "verbose_name": "Mazeret Günü",
                "verbose_name_plural": "Mazeret Günleri",
                "ordering": ["tarih"],
            },
        ),
        migrations.CreateModel(
            name="MazeretOturum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oturum_no",
                    models.PositiveSmallIntegerField(verbose_name="Oturum No"),
                ),
                ("saat_baslangic", models.TimeField(verbose_name="Başlangıç Saati")),
                ("saat_bitis", models.TimeField(verbose_name="Bitiş Saati")),
                (
                    "sinav_turu",
                    models.CharField(
                        choices=[("Yazili", "Yazılı"), ("Uygulama", "Uygulama")],
                        default="Yazili",
                        max_length=20,
                        verbose_name="Sınav Türü",
                    ),
                ),
                (
                    "gun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oturumlar",
                        to="sinav.mazeretgun",
                        verbose_name="Gün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mazeret Oturumu",
                "verbose_name_plural": "Mazeret Oturumları",
                "ordering": ["gun__tarih", "oturum_no"],
                "unique_together": {("gun", "oturum_no")},
            },
        ),
        migrations.CreateModel(
            name="MazeretSinav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Açıklama"
                    ),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "sinav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mazeret_sinavlar",
                        to="sinav.sinavbilgisi",
                        verbose_name="Sınav",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mazeret Sınav",
                "verbose_name_plural": "Mazeret Sınavları",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
        migrations.AddField(
            model_name="mazeretgun",
            name="mazeret_sinav",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gunler",
                to="sinav.mazeretsinav",
                verbose_name="Mazeret Sınavı",
            ),
        ),
        migrations.CreateModel(
            name="MazeretOturumDers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sinav_turu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Normal"),
                            ("Yazili", "Yazılı"),
                            ("Uygulama", "Uygulama"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Sınav Türü",
                    ),
                ),
                (
                    "ders",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="okul.dershavuzu",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "oturum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dersler",
                        to="sinav.mazeretoturum",
                        verbose_name="Oturum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mazeret Oturum Dersi",
                "verbose_name_plural": "Mazeret Oturum Dersleri",
                "ordering": ["oturum__oturum_no", "ders"],
                "unique_together": {("oturum", "ders", "sinav_turu")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="mazeretgun",
            unique_together={("mazeret_sinav", "tarih")},
        ),
    ]
