# Generated by Django 6.0.3 on 2026-04-14 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0050_mazeret_sinav"),
    ]

    operations = [
        migrations.CreateModel(
            name="MazeretOgrenci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("okulno", models.CharField(max_length=20, verbose_name="Okul No")),
                (
                    "adi_soyadi",
                    models.CharField(max_length=200, verbose_name="Adı Soyadı"),
                ),
                (
                    "sinifsube",
                    models.CharField(max_length=10, verbose_name="Sınıf/Şube"),
                ),
                ("ders_adi", models.CharField(max_length=200, verbose_name="Ders Adı")),
                (
                    "sinav_turu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Normal"),
                            ("Yazili", "Yazılı"),
                            ("Uygulama", "Uygulama"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Sınav Türü",
                    ),
                ),
                (
                    "belge_teslim",
                    models.BooleanField(
                        default=False,
                        help_text="Geçerli mazeret belgesi idareye teslim edildi.",
                        verbose_name="Belge Teslim",
                    ),
                ),
                (
                    "mazeret_sinav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ogrenciler",
                        to="sinav.mazeretsinav",
                        verbose_name="Mazeret Sınav",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mazeret Öğrenci",
                "verbose_name_plural": "Mazeret Öğrencileri",
                "ordering": ["sinifsube", "okulno", "ders_adi"],
                "unique_together": {
                    ("mazeret_sinav", "okulno", "ders_adi", "sinav_turu")
                },
            },
        ),
    ]
