# Generated by Django 6.0.3 on 2026-04-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0051_mazeret_ogrenci"),
    ]

    operations = [
        migrations.CreateModel(
            name="MazeretBelgeTeslim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sinav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="belge_teslimler",
                        to="sinav.sinavbilgisi",
                        verbose_name="Sınav",
                    ),
                ),
                ("okulno", models.CharField(max_length=20, verbose_name="Okul No")),
                ("ders_adi", models.CharField(max_length=200, verbose_name="Ders Adı")),
                (
                    "sinav_turu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Normal"),
                            ("Yazili", "Yazılı"),
                            ("Uygulama", "Uygulama"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Sınav Türü",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mazeret Belge Teslim",
                "verbose_name_plural": "Mazeret Belge Teslimleri",
                "unique_together": {("sinav", "okulno", "ders_adi", "sinav_turu")},
            },
        ),
    ]
