# Generated by Django 6.0.3 on 2026-04-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0052_mazeret_belge_teslim"),
    ]

    operations = [
        migrations.AddField(
            model_name="mazeretsinav",
            name="onay_tarihi",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Onay Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="mazeretsinav",
            name="onaylandi",
            field=models.BooleanField(default=False, verbose_name="Onaylandı"),
        ),
        migrations.CreateModel(
            name="MazeretOturmaPlani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salon",
                    models.CharField(
                        choices=[("Mazeret1", "Mazeret1"), ("Mazeret2", "Mazeret2")],
                        max_length=20,
                        verbose_name="Salon",
                    ),
                ),
                ("sira_no", models.PositiveSmallIntegerField(verbose_name="Sıra No")),
                ("okulno", models.CharField(max_length=20, verbose_name="Okul No")),
                (
                    "adi_soyadi",
                    models.CharField(max_length=200, verbose_name="Adı Soyadı"),
                ),
                (
                    "sinifsube",
                    models.CharField(max_length=10, verbose_name="Sınıf/Şube"),
                ),
                ("ders_adi", models.CharField(max_length=200, verbose_name="Ders Adı")),
                (
                    "sinav_turu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Normal"),
                            ("Yazili", "Yazılı"),
                            ("Uygulama", "Uygulama"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Sınav Türü",
                    ),
                ),
                (
                    "mazeret_sinav",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oturma_plani",
                        to="sinav.mazeretsinav",
                        verbose_name="Mazeret Sınav",
                    ),
                ),
                (
                    "oturum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oturma_plani",
                        to="sinav.mazeretoturum",
                        verbose_name="Oturum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mazeret Oturma Planı",
                "verbose_name_plural": "Mazeret Oturma Planları",
                "ordering": [
                    "oturum__gun__tarih",
                    "oturum__oturum_no",
                    "salon",
                    "sira_no",
                ],
                "unique_together": {("oturum", "salon", "sira_no")},
            },
        ),
    ]
