# Generated by Django 6.0.3 on 2026-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0053_mazeret_oturma_plani"),
    ]

    operations = [
        migrations.AddField(
            model_name="algoritmaparametreleri",
            name="kelebek_dagitim",
            field=models.BooleanField(
                default=True,
                help_text="Seçili: öğrenciler salonlara karışık dağıtılır. Seçili değil: her sınıf kendi salonunda sınava girer.",
                verbose_name="Kelebek Dağılımı",
            ),
        ),
    ]
