# Generated by Django 6.0.3 on 2026-05-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0054_algoritma_kelebek_dagitim"),
    ]

    operations = [
        migrations.AddField(
            model_name="algoritmaparametreleri",
            name="max_sinav_per_gun",
            field=models.IntegerField(
                default=2,
                help_text="Bir öğrencinin (şubenin) aynı günde girebileceği en fazla sınav sayısı. ILP kısıtı bu değerle uygulanır.",
                verbose_name="Günde Maks. Sınav Sayısı",
            ),
        ),
    ]
