# Generated by Django 6.0.3 on 2026-05-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0055_algoritma_max_sinav_per_gun"),
    ]

    operations = [
        migrations.AddField(
            model_name="takvimuretim",
            name="aciklama",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Açıklama"
            ),
        ),
    ]
