# Generated by Django 6.0.3 on 2026-05-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0056_takvim_uretim_aciklama"),
    ]

    operations = [
        migrations.AddField(
            model_name="mazeretsinav",
            name="baslangic_tarihi",
            field=models.DateField(
                blank=True, null=True, verbose_name="ILP Başlangıç Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="mazeretsinav",
            name="oturum_saatleri",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Virgülle ayrılmış HH:MM listesi. Boşsa AlgoritmaParametreleri'nden okunur.",
                max_length=200,
                verbose_name="Oturum Saatleri",
            ),
        ),
    ]
