# Generated by Django 6.0.3 on 2026-05-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0057_mazeretsinav_ilp_alanlari"),
    ]

    operations = [
        migrations.AddField(
            model_name="mazeretsinav",
            name="salon_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"Mazeret 1": 36, "Mazeret 2": 36} formatında salon adı → kapasite.',
                verbose_name="Salon Yapılandırması",
            ),
        ),
        migrations.AlterField(
            model_name="mazeretoturmaplani",
            name="salon",
            field=models.CharField(max_length=50, verbose_name="Salon"),
        ),
    ]
