# Generated by Django 6.0.3 on 2026-07-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0058_mazeretsinav_salon_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazeretsinav',
            name='max_sinav_per_gun',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Bir öğrencinin aynı günde girebileceği en fazla oturum sayısı. Boşsa AlgoritmaParametreleri'nden okunur.", null=True, verbose_name='Günde Maks. Oturum Sayısı'),
        ),
    ]
