# Generated by Django 6.0.3 on 2026-07-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0059_mazeretsinav_max_sinav_per_gun'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazeretsinav',
            name='tatil_gunleri',
            field=models.TextField(blank=True, default='', help_text='Virgülle veya satırla ayrılmış YYYY-MM-DD listesi. Bu günlere sınav planlanmaz. Sınavın genel tatil günlerine ek olarak uygulanır.', verbose_name='Tatil Günleri'),
        ),
    ]
