# Generated by Django 6.0.3 on 2026-08-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0060_mazeretsinav_tatil_gunleri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algoritmaparametreleri',
            name='max_sinav_per_gun',
            field=models.IntegerField(default=2, help_text='Bir öğrencinin (şubenin) aynı günde girebileceği en fazla sınav sayısı. Sert kısıt bu değerle uygulanır.', verbose_name='Günde Maks. Sınav Sayısı'),
        ),
    ]
