# Generated by Django 6.0.3 on 2026-09-06 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0061_alter_algoritmaparametreleri_max_sinav_per_gun'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinavOgrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okulno', models.PositiveIntegerField(verbose_name='Okul No')),
                ('adi', models.CharField(max_length=150, verbose_name='Adı')),
                ('soyadi', models.CharField(max_length=150, verbose_name='Soyadı')),
                ('cinsiyet', models.CharField(blank=True, max_length=1, verbose_name='Cinsiyet')),
                ('sinif', models.IntegerField(verbose_name='Sınıf')),
                ('sube', models.CharField(max_length=2, verbose_name='Şube')),
                ('sureksiz_devamsiz', models.BooleanField(default=False, verbose_name='Sürekli Devamsız')),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinav_ogrencileri', to='sinav.sinavbilgisi', verbose_name='Sınav')),
            ],
            options={
                'verbose_name': 'Sınav Öğrencisi (Anlık Görüntü)',
                'verbose_name_plural': 'Sınav Öğrencileri (Anlık Görüntü)',
                'unique_together': {('sinav', 'okulno')},
            },
        ),
        migrations.CreateModel(
            name='SinavOgrenciMuaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okulno', models.PositiveIntegerField(verbose_name='Okul No')),
                ('ders_adi', models.CharField(max_length=200, verbose_name='Ders Adı')),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogrenci_muafiyetleri', to='sinav.sinavbilgisi', verbose_name='Sınav')),
            ],
            options={
                'verbose_name': 'Sınav Öğrencisi Muafiyeti (Anlık Görüntü)',
                'verbose_name_plural': 'Sınav Öğrencisi Muafiyetleri (Anlık Görüntü)',
                'unique_together': {('sinav', 'okulno', 'ders_adi')},
            },
        ),
    ]
