# Generated by Django 6.0.3 on 2026-09-07 21:26

import django.db.models.deletion
import django.utils.timezone
import ebagiris.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('okul', '0023_alter_brans_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbaHesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eba_id', models.CharField(max_length=64, unique=True, verbose_name='EBA Kimliği')),
                ('eba_adi_soyadi', models.CharField(blank=True, max_length=150, verbose_name="EBA'daki Ad Soyad")),
                ('baglanma_zamani', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bağlanma Zamanı')),
                ('personel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eba_hesap', to='okul.personel', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'EBA Hesabı',
                'verbose_name_plural': 'EBA Hesapları',
                'db_table': 'ebagiris_hesap',
            },
        ),
        migrations.CreateModel(
            name='EbaOturum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=ebagiris.models._yeni_token, editable=False, max_length=32, unique=True)),
                ('amac', models.CharField(choices=[('giris', 'Giriş'), ('baglama', 'Hesap Bağlama')], max_length=10, verbose_name='Amaç')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('qr_hazir', 'QR Hazır'), ('dogrulandi', 'Doğrulandı'), ('tamamlandi', 'Tamamlandı'), ('suresi_doldu', 'Süresi Doldu'), ('hata', 'Hata')], default='bekliyor', max_length=15, verbose_name='Durum')),
                ('qr_uuid', models.CharField(blank=True, max_length=64, verbose_name='QR İçeriği')),
                ('qr_expire_at', models.DateTimeField(blank=True, null=True, verbose_name='QR Son Kullanma')),
                ('eba_id', models.CharField(blank=True, max_length=64, verbose_name='Doğrulanan EBA Kimliği')),
                ('eba_adi_soyadi', models.CharField(blank=True, max_length=150, verbose_name="EBA'daki Ad Soyad")),
                ('mesaj', models.CharField(blank=True, max_length=300, verbose_name='Mesaj')),
                ('olusturma_zamani', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_zamani', models.DateTimeField(auto_now=True)),
                ('baglanacak_personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='okul.personel', verbose_name='Bağlanacak Personel')),
                ('eslesen_personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='okul.personel', verbose_name='Eşleşen Personel')),
            ],
            options={
                'verbose_name': 'EBA Oturumu',
                'verbose_name_plural': 'EBA Oturumları',
                'db_table': 'ebagiris_oturum',
                'ordering': ['-olusturma_zamani'],
            },
        ),
    ]
