# Generated by Django 6.0.3 on 2026-09-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebagiris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaoturum',
            name='baslatan_session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='ebaoturum',
            name='istek_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='İstek IP'),
        ),
    ]
