# Generated by Django 6.0.3 on 2026-03-15 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nobet", "0010_nobetpersonel_user"),
        ("ogrenci", "0003_ogrencidevamsizlik"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faaliyet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "konu",
                    models.CharField(max_length=300, verbose_name="Faaliyet Konusu"),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                ("yer", models.CharField(max_length=200, verbose_name="Yapıldığı Yer")),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                ("olusturma_zamani", models.DateTimeField(auto_now_add=True)),
                (
                    "ogrenciler",
                    models.ManyToManyField(
                        blank=True,
                        related_name="faaliyetler",
                        to="ogrenci.ogrenci",
                        verbose_name="Katılan Öğrenciler",
                    ),
                ),
                (
                    "ogretmen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faaliyetler",
                        to="nobet.nobetpersonel",
                        verbose_name="Öğretmen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faaliyet",
                "verbose_name_plural": "Faaliyetler",
                "db_table": "faaliyet",
                "ordering": ["-tarih", "-olusturma_zamani"],
            },
        ),
        migrations.CreateModel(
            name="FaaliyetDersSaati",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ders_no", models.PositiveSmallIntegerField(verbose_name="Ders No")),
                ("baslangic", models.TimeField(verbose_name="Başlangıç")),
                ("bitis", models.TimeField(verbose_name="Bitiş")),
                (
                    "faaliyet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ders_saatleri",
                        to="faaliyet.faaliyet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faaliyet Ders Saati",
                "db_table": "faaliyet_ders_saati",
                "ordering": ["ders_no"],
                "unique_together": {("faaliyet", "ders_no")},
            },
        ),
    ]
