# Generated by Django 6.0.3 on 2026-03-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faaliyet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faaliyet",
            name="devamsizlik_girildi",
            field=models.BooleanField(default=False, verbose_name="Devamsızlık Girildi"),
        ),
        migrations.AddField(
            model_name="faaliyet",
            name="durum",
            field=models.CharField(
                choices=[
                    ("beklemede", "Onay Bekliyor"),
                    ("onaylandi", "Onaylandı"),
                    ("reddedildi", "Reddedildi"),
                ],
                default="beklemede",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AddField(
            model_name="faaliyet",
            name="ret_aciklamasi",
            field=models.TextField(blank=True, verbose_name="Red Açıklaması"),
        ),
    ]
