# Generated by Django 6.0.3 on 2026-03-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faaliyet", "0002_faaliyet_devamsizlik_girildi_faaliyet_durum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faaliyet",
            name="onay_zamani",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Onay Tarihi"),
        ),
        migrations.AddField(
            model_name="faaliyet",
            name="onaylayan_adi",
            field=models.CharField(blank=True, max_length=200, verbose_name="Onaylayan"),
        ),
    ]
