# Generated by Django 6.0.3 on 2026-09-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faaliyet', '0004_update_nobetpersonel_fk_to_okul'),
    ]

    operations = [
        migrations.AddField(
            model_name='faaliyet',
            name='arsivlendi',
            field=models.BooleanField(default=False, help_text='Sene Sonu Geçişi uygulandığında geçmiş eğitim-öğretim yılına ait faaliyet kayıtları otomatik olarak arşivlenir; arşivlenen kayıtlar varsayılan yönetim listesinde görünmez (tarih filtresiyle aranabilir).', verbose_name='Arşivlendi'),
        ),
    ]
