# Generated by Django 6.0.3 on 2026-03-16 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("disiplin", "0002_remove_disiplincagri_state"),
        ("nobet", "0012_remove_devamsizlik"),
        ("ogrenci", "0004_remove_ogrencidevamsizlik"),
        ("rehberlik", "0005_remove_ogrencicagri_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OgrenciCagri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "servis",
                    models.CharField(
                        choices=[
                            ("rehberlik", "Rehberlik"),
                            ("disiplin", "Disiplin"),
                            ("muduriyetcagri", "Müdüriyet"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Servis",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "ders_saati",
                    models.IntegerField(blank=True, null=True, verbose_name="Ders Saati"),
                ),
                (
                    "ders_adi",
                    models.CharField(blank=True, max_length=100, verbose_name="Ders Adı"),
                ),
                (
                    "ogretmen_adi",
                    models.CharField(blank=True, max_length=100, verbose_name="Dersin Öğretmeni"),
                ),
                (
                    "cagri_metni",
                    models.TextField(blank=True, verbose_name="Çağrı Metni"),
                ),
                ("olusturma_zamani", models.DateTimeField(auto_now_add=True)),
                (
                    "gorusme_disiplin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="disiplin.disiplingorusme",
                        verbose_name="Disiplin Görüşmesi",
                    ),
                ),
                (
                    "gorusme_rehberlik",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="rehberlik.gorusme",
                        verbose_name="Rehberlik Görüşmesi",
                    ),
                ),
                (
                    "kayit_eden",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="nobet.nobetpersonel",
                        verbose_name="Kaydeden (Personel)",
                    ),
                ),
                (
                    "kayit_eden_kullanici",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kaydeden (Kullanıcı)",
                    ),
                ),
                (
                    "ogrenci",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ogrenci.ogrenci",
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci Çağrısı",
                "verbose_name_plural": "Öğrenci Çağrıları",
                "db_table": "cagri_ogrencicagri",
                "ordering": ["-tarih", "ders_saati"],
            },
        ),
    ]
