# Generated by Django 6.0.3 on 2026-03-16 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cagri", "0002_migrate_data"),
        ("muduriyetcagri", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ogrencicagri",
            name="gorusme_muduriyetcagri",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="muduriyetcagri.muduriyetgorusme",
                verbose_name="Müdüriyet Görüşmesi",
            ),
        ),
    ]
