# Generated by Django 6.0.3 on 2026-03-29 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("okul", "0011_add_dershavuzu_sinav_alanlari"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SinifTahta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_adresi",
                    models.GenericIPAddressField(
                        protocol="IPv4", verbose_name="IP Adresi"
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(default=8765, verbose_name="Port"),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Açıklama"
                    ),
                ),
                (
                    "sinif_sube",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tahta",
                        to="okul.sinifsube",
                        verbose_name="Sınıf/Şube",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sınıf Tahtası",
                "verbose_name_plural": "Sınıf Tahtaları",
                "ordering": ["sinif_sube__sinif", "sinif_sube__sube"],
            },
        ),
        migrations.CreateModel(
            name="BildirimLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tur",
                    models.CharField(
                        choices=[
                            ("cagri", "Öğrenci Çağrısı"),
                            ("duyuru", "Duyuru"),
                            ("test", "Test"),
                        ],
                        max_length=10,
                        verbose_name="Tür",
                    ),
                ),
                ("baslik", models.CharField(max_length=200, verbose_name="Başlık")),
                ("mesaj", models.TextField(verbose_name="Mesaj")),
                (
                    "gonderim_zamani",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Gönderim Zamanı"
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[("basarili", "Başarılı"), ("basarisiz", "Başarısız")],
                        max_length=12,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "hata_mesaji",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "gonderen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gönderen",
                    ),
                ),
                (
                    "tahta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bildirimler",
                        to="bildirim_gonderici.siniftahta",
                        verbose_name="Hedef Tahta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim Kaydı",
                "verbose_name_plural": "Bildirim Kayıtları",
                "ordering": ["-gonderim_zamani"],
            },
        ),
    ]
