# Generated by Django 6.0.3 on 2026-03-24 00:48

import django.db.models.deletion
import sinavmedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sinav", "0035_takvimuretim_onizleme_verisi"),
    ]

    operations = [
        migrations.CreateModel(
            name="SinavMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seviye",
                    models.IntegerField(
                        choices=[
                            (9, "9. Sınıf"),
                            (10, "10. Sınıf"),
                            (11, "11. Sınıf"),
                            (12, "12. Sınıf"),
                        ]
                    ),
                ),
                (
                    "dosya",
                    models.FileField(
                        upload_to=sinavmedia.models.sinav_media_upload_path
                    ),
                ),
                ("aciklama", models.CharField(blank=True, default="", max_length=300)),
                (
                    "serbest",
                    models.BooleanField(
                        default=False,
                        help_text="İşaretlenirse sınav saati kısıtı kaldırılır, her zaman oynatılabilir.",
                    ),
                ),
                (
                    "takvim",
                    models.ForeignKey(
                        limit_choices_to={"ders_adi__icontains": "(Uygulama)"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medyalar",
                        to="sinav.takvim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sınav Medyası",
                "verbose_name_plural": "Sınav Medyaları",
                "ordering": ["takvim__tarih", "takvim__saat", "seviye"],
                "unique_together": {("takvim", "seviye")},
            },
        ),
    ]
