# Generated by Django 6.0.3 on 2026-05-28 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinav", "0058_mazeretsinav_salon_config"),
        ("sinavmedia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sinavmedia",
            name="takvim",
            field=models.ForeignKey(
                limit_choices_to={"sinav_turu": "Uygulama"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medyalar",
                to="sinav.takvim",
            ),
        ),
    ]
