# Generated by Django 6.0.3 on 2026-03-14 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ogrenci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "okulno",
                    models.CharField(max_length=20, unique=True, verbose_name="Okul No"),
                ),
                ("sinif", models.IntegerField(verbose_name="Sınıf")),
                ("sube", models.CharField(max_length=2, verbose_name="Şube")),
                (
                    "tckimlikno",
                    models.CharField(max_length=11, unique=True, verbose_name="TC Kimlik No"),
                ),
                ("adi", models.CharField(max_length=50, verbose_name="Adı")),
                ("soyadi", models.CharField(max_length=50, verbose_name="Soyadı")),
                ("dogumtarihi", models.DateField(verbose_name="Doğum Tarihi")),
                (
                    "cinsiyet",
                    models.CharField(
                        choices=[("E", "Erkek"), ("K", "Kız")],
                        max_length=1,
                        verbose_name="Cinsiyet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci",
                "verbose_name_plural": "Öğrenciler",
                "db_table": "ogrenci",
                "ordering": ["sinif", "sube", "soyadi", "adi"],
            },
        ),
        migrations.CreateModel(
            name="OgrenciAdres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "il",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="İl"),
                ),
                (
                    "ilce",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="İlçe"),
                ),
                (
                    "mahalle",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Mahalle"),
                ),
                (
                    "postakodu",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Posta Kodu"
                    ),
                ),
                (
                    "adres",
                    models.TextField(blank=True, null=True, verbose_name="Adres"),
                ),
                (
                    "ogrenci",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adres",
                        to="ogrenci.ogrenci",
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci Adres",
                "verbose_name_plural": "Öğrenci Adresleri",
                "db_table": "ogrenci_adres",
            },
        ),
        migrations.CreateModel(
            name="OgrenciDetay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "babaadi",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Baba Adı"
                    ),
                ),
                (
                    "anneadi",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Anne Adı"
                    ),
                ),
                (
                    "veli",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Veli"),
                ),
                (
                    "velitelefon",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Veli Telefon",
                    ),
                ),
                (
                    "annetelefon",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Anne Telefon",
                    ),
                ),
                (
                    "babatelefon",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Baba Telefon",
                    ),
                ),
                (
                    "ogrenci",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detay",
                        to="ogrenci.ogrenci",
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci Detay",
                "verbose_name_plural": "Öğrenci Detayları",
                "db_table": "ogrenci_detay",
            },
        ),
    ]
