# Generated by Django 6.0.3 on 2026-03-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ogrenci", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ogrenci",
            name="adi",
            field=models.CharField(max_length=150, verbose_name="Adı"),
        ),
        migrations.AlterField(
            model_name="ogrenci",
            name="soyadi",
            field=models.CharField(max_length=150, verbose_name="Soyadı"),
        ),
    ]
