# Generated by Django 6.0.3 on 2026-03-16 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ogrenci", "0004_remove_ogrencidevamsizlik"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ogrenci",
            options={
                "ordering": ["sinif", "sube", "okulno"],
                "verbose_name": "Öğrenci",
                "verbose_name_plural": "Öğrenciler",
            },
        ),
    ]
