# Generated by Django 6.0.3 on 2026-04-01 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ogrenci", "0005_alter_ogrenci_options"),
        ("okul", "0011_add_dershavuzu_sinav_alanlari"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SinifOturmaDuzeni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sira_no", models.PositiveSmallIntegerField(verbose_name="Sıra No")),
                ("kolon_no", models.PositiveSmallIntegerField(verbose_name="Kolon No")),
                (
                    "guncelleme",
                    models.DateTimeField(auto_now=True, verbose_name="Son Güncelleme"),
                ),
                (
                    "guncelleyen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Güncelleyen",
                    ),
                ),
                (
                    "ogrenci",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oturma_duzeni",
                        to="ogrenci.ogrenci",
                        verbose_name="Öğrenci",
                    ),
                ),
                (
                    "sinif_sube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oturma_duzeni",
                        to="okul.sinifsube",
                        verbose_name="Sınıf/Şube",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sınıf Oturma Düzeni",
                "verbose_name_plural": "Sınıf Oturma Düzenleri",
                "db_table": "sinif_oturma_duzeni",
                "ordering": ["sinif_sube", "sira_no", "kolon_no"],
                "unique_together": {("sinif_sube", "sira_no", "kolon_no")},
            },
        ),
    ]
