# Generated by Django 6.0.3 on 2026-04-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ogrenci", "0006_sinif_oturma_duzeni"),
    ]

    operations = [
        migrations.AddField(
            model_name="ogrenci",
            name="sureksiz_devamsiz",
            field=models.BooleanField(
                default=False,
                help_text="İşaretlenirse mazeret sınavına çağrılmaz.",
                verbose_name="Sürekli Devamsız",
            ),
        ),
    ]
