# Generated by Django 6.0.3 on 2026-04-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ogrenci", "0007_sureksiz_devamsiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="ogrenci",
            name="muaf",
            field=models.BooleanField(
                default=False,
                help_text="İşaretlenirse mazeret sınavına alınmaz.",
                verbose_name="Muaf",
            ),
        ),
    ]
