# Generated by Django 6.0.3 on 2026-04-14 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ogrenci", "0008_muaf"),
        ("okul", "0011_add_dershavuzu_sinav_alanlari"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ogrenci",
            name="muaf",
        ),
        migrations.CreateModel(
            name="OgrenciMuaf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ders",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="okul.dershavuzu",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "ogrenci",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muaf_dersler",
                        to="ogrenci.ogrenci",
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci Muaf Ders",
                "verbose_name_plural": "Öğrenci Muaf Dersleri",
                "ordering": ["ogrenci", "ders__ders_adi"],
                "unique_together": {("ogrenci", "ders")},
            },
        ),
    ]
