# Generated by Django 6.0.3 on 2026-05-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ogrenci", "0009_ogrencimuaf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ogrenci",
            name="okulno",
            field=models.PositiveIntegerField(unique=True, verbose_name="Okul No"),
        ),
    ]
