# Generated by Django 6.0.3 on 2026-07-01 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0010_okulno_charfield_to_positiveinteger'),
        ('okul', '0012_add_aktif_veri_konfigurasyonu'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ogrencimuaf',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sinifoturmaduzeni',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ogrencimuaf',
            name='egitim_yili',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='okul.egitimogretimyili', verbose_name='Eğitim-Öğretim Yılı'),
        ),
        migrations.AddField(
            model_name='sinifoturmaduzeni',
            name='egitim_yili',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='okul.egitimogretimyili', verbose_name='Eğitim-Öğretim Yılı'),
        ),
        migrations.AlterUniqueTogether(
            name='ogrencimuaf',
            unique_together={('egitim_yili', 'ogrenci', 'ders')},
        ),
        migrations.AlterUniqueTogether(
            name='sinifoturmaduzeni',
            unique_together={('egitim_yili', 'sinif_sube', 'sira_no', 'kolon_no')},
        ),
    ]
