# Generated by Django 6.0.3 on 2026-07-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0012_egitim_yili_veri_damgasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='aktif',
            field=models.BooleanField(default=True, help_text='Tasdikname alan (öğrenim hakkını kullanmış) öğrenciler için otomatik olarak pasife alınır ve aktif öğrenci listelerinden çıkarılır.', verbose_name='Aktif'),
        ),
    ]
