# Generated by Django 6.0.3 on 2026-07-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0013_ogrenci_aktif'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='sectigi_alan',
            field=models.CharField(blank=True, default='YOK', help_text="11-12. sınıfta MF/TM/DİL gibi seçilen alan adı; 9-10. sınıf ve alan seçimi yapılmamış öğrenciler için 'YOK'.", max_length=20, verbose_name='Seçtiği Alan'),
        ),
    ]
