# Generated by Django 6.0.3 on 2026-08-14 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0014_ogrenci_sectigi_alan'),
        ('okul', '0019_sinifsube_acik'),
    ]

    operations = [
        migrations.CreateModel(
            name='OgrenciAyrilma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sebep', models.CharField(choices=[('nakil', 'Nakil'), ('ogrenim_hakki', 'Öğrenim Hakkını Tamamladı'), ('mesem', 'Mesem Sistemine Kayıt'), ('yurtdisi', 'Yurt Dışına Çıktı'), ('vefat', 'Vefat'), ('diger', 'Diğer')], max_length=20, verbose_name='Ayrılma Sebebi')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='Ayrılma Tarihi')),
                ('aciklama', models.CharField(blank=True, max_length=300, verbose_name='Açıklama')),
                ('olusturma', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('egitim_yili', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ogrenci_ayrilmalari', to='okul.egitimogretimyili', verbose_name='Eğitim-Öğretim Yılı')),
                ('ogrenci', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ayrilma', to='ogrenci.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Öğrenci Ayrılma Bilgisi',
                'verbose_name_plural': 'Öğrenci Ayrılma Bilgileri',
                'db_table': 'ogrenci_ayrilma',
                'ordering': ['-olusturma'],
            },
        ),
    ]
