# Generated by Django 6.0.3 on 2026-03-16 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("muduriyetcagri", "0002_remove_muduriycagri"),
        ("ogrenci", "0004_remove_ogrencidevamsizlik"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MuduriyetGorusme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "veli_adi",
                    models.CharField(blank=True, max_length=200, verbose_name="Veli Adı Soyadı"),
                ),
                (
                    "veli_telefon",
                    models.CharField(blank=True, max_length=30, verbose_name="Veli Telefonu"),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "tur",
                    models.CharField(
                        choices=[
                            ("bireysel", "Bireysel Öğrenci"),
                            ("veli", "Veli Görüşmesi"),
                            ("grup", "Grup Görüşmesi"),
                            ("diger", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Görüşme Türü",
                    ),
                ),
                ("konu", models.CharField(max_length=300, verbose_name="Konu")),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "sonuc",
                    models.TextField(blank=True, verbose_name="Alınan Karar / Sonuç"),
                ),
                (
                    "takip_tarihi",
                    models.DateField(blank=True, null=True, verbose_name="Takip Tarihi"),
                ),
                ("olusturma_zamani", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_zamani", models.DateTimeField(auto_now=True)),
                (
                    "grup_ogrencileri",
                    models.ManyToManyField(
                        blank=True,
                        related_name="muduriyetcagri_grup_gorusmeleri",
                        to="ogrenci.ogrenci",
                        verbose_name="Grup Öğrencileri",
                    ),
                ),
                (
                    "kayit_eden_kullanici",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="muduriyetcagri_gorusmeleri",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kaydeden",
                    ),
                ),
                (
                    "ogrenci",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="muduriyetcagri_gorusmeleri",
                        to="ogrenci.ogrenci",
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Müdüriyet Görüşmesi",
                "verbose_name_plural": "Müdüriyet Görüşmeleri",
                "db_table": "muduriyetcagri_gorusme",
                "ordering": ["-tarih", "-olusturma_zamani"],
            },
        ),
    ]
