# Generated by Django 6.0.3 on 2026-05-03 19:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("okul", "0012_add_aktif_veri_konfigurasyonu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GorevTipi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kod",
                    models.CharField(
                        choices=[
                            ("mudur", "Okul Müdürü"),
                            ("mudur_yardimcisi", "Müdür Yardımcısı"),
                            ("brans_ogretmeni", "Öğretmen"),
                            ("rehber_ogretmen", "Rehberlik"),
                            ("ucretli_ogretmen", "Ücretli Öğretmen"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="Kod",
                    ),
                ),
                ("ad", models.CharField(max_length=50, verbose_name="Ad")),
                (
                    "maas_karsiligi_haftalik",
                    models.IntegerField(
                        default=0,
                        help_text="Bu göreve ait haftalık ders saatinin maaşa dahil kısmı.",
                        verbose_name="Maaş Karşılığı (saat/hafta)",
                    ),
                ),
                (
                    "hazirlik_katsayi",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="0.50 → her 2 saate 1 saat ek hazırlık (ücretli öğretmen için).",
                        max_digits=3,
                        verbose_name="Hazırlık Katsayısı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Görev Tipi",
                "verbose_name_plural": "Görev Tipleri",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="Tatil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100, verbose_name="Tatil Adı")),
                ("baslangic", models.DateField(verbose_name="Başlangıç")),
                ("bitis", models.DateField(verbose_name="Bitiş")),
            ],
            options={
                "verbose_name": "Tatil",
                "verbose_name_plural": "Tatiller",
                "ordering": ["baslangic"],
            },
        ),
        migrations.CreateModel(
            name="EkDersDonemi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100, verbose_name="Dönem Adı")),
                ("baslangic_tarihi", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("bitis_tarihi", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "hafta_sayisi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Boş bırakılırsa tatil günleri düşülerek otomatik hesaplanır.",
                        max_digits=5,
                        null=True,
                        verbose_name="Hafta Sayısı",
                    ),
                ),
                ("kapandi", models.BooleanField(default=False, verbose_name="Kapalı")),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "olusturan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ek Ders Dönemi",
                "verbose_name_plural": "Ek Ders Dönemleri",
                "ordering": ["-baslangic_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="EkDersOnay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("onay_tarihi", models.DateTimeField(auto_now_add=True)),
                ("notlar", models.TextField(blank=True, default="")),
                (
                    "donem",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onay",
                        to="ekders.ekdersdonemi",
                    ),
                ),
                (
                    "onaylayan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Onaylayan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ek Ders Onayı",
                "verbose_name_plural": "Ek Ders Onayları",
            },
        ),
        migrations.CreateModel(
            name="OgretmenEkDers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hafta_baslangic",
                    models.DateField(verbose_name="Hafta Başlangıcı (Pazartesi)"),
                ),
                ("pazartesi", models.IntegerField(default=0)),
                ("sali", models.IntegerField(default=0)),
                ("carsamba", models.IntegerField(default=0)),
                ("persembe", models.IntegerField(default=0)),
                ("cuma", models.IntegerField(default=0)),
                ("cumartesi", models.IntegerField(default=0)),
                ("pazar", models.IntegerField(default=0)),
                (
                    "nobet_sayisi",
                    models.IntegerField(default=0, verbose_name="Nöbet Sayısı"),
                ),
                (
                    "diger_zorunlu_saat",
                    models.IntegerField(default=0, verbose_name="Diğer Zorunlu Saat"),
                ),
                ("notlar", models.TextField(blank=True, default="")),
                (
                    "donem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kayitlar",
                        to="ekders.ekdersdonemi",
                    ),
                ),
                (
                    "gorev_tipi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ekders.gorevtipi",
                    ),
                ),
                (
                    "personel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ekders_kayitlari",
                        to="okul.personel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğretmen Ek Ders (Haftalık)",
                "verbose_name_plural": "Öğretmen Ek Ders Kayıtları",
                "ordering": ["hafta_baslangic", "personel__adi_soyadi"],
                "unique_together": {("donem", "personel", "hafta_baslangic")},
            },
        ),
    ]
