# Generated by Django 6.0.3 on 2026-03-16 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ogrenci", "0004_remove_ogrencidevamsizlik"),
    ]

    operations = [
        migrations.CreateModel(
            name="OgrenciNobetGorevi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "olusturan",
                    models.CharField(blank=True, max_length=100, verbose_name="Oluşturan"),
                ),
                ("olusturma_zamani", models.DateTimeField(auto_now_add=True)),
                (
                    "ogrenci",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nobet_gorevleri",
                        to="ogrenci.ogrenci",
                        verbose_name="Öğrenci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Öğrenci Nöbet Görevi",
                "verbose_name_plural": "Öğrenci Nöbet Görevleri",
                "ordering": [
                    "-tarih",
                    "ogrenci__sinif",
                    "ogrenci__sube",
                    "ogrenci__soyadi",
                ],
                "unique_together": {("ogrenci", "tarih")},
            },
        ),
    ]
