# Generated by Django 6.0.3 on 2026-09-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrencinobet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrencinobetgorevi',
            name='arsivlendi',
            field=models.BooleanField(default=False, help_text='Sene Sonu Geçişi uygulandığında geçmiş eğitim-öğretim yılına ait görevler otomatik olarak arşivlenir; arşivlenen görevler öğrenciyi yeni yılda nöbetçi seçiminde engellemez, yalnızca bilgi amaçlı gösterilir.', verbose_name='Arşivlendi'),
        ),
    ]
