# Generated by Django 6.0.3 on 2026-03-27 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dersprogrami", "0007_remove_old_ders_saati_fields"),
        ("okul", "0004_add_ders_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="dersprogrami",
            name="ders_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dersprogrami",
                to="okul.dershavuzu",
                verbose_name="Ders",
            ),
        ),
    ]
