# Generated by Django 6.0.3 on 2026-07-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersprogrami', '0010_replace_ders_adi_field'),
        ('okul', '0018_alter_personel_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='dersprogrami',
            name='donem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ders_programlari', to='okul.okuldonem', verbose_name='Dönem'),
        ),
        migrations.AddField(
            model_name='dersprogrami',
            name='egitim_yili',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ders_programlari', to='okul.egitimogretimyili', verbose_name='Eğitim-Öğretim Yılı'),
        ),
    ]
