# Generated by Django 6.0.3 on 2026-09-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersprogrami', '0012_egitim_yili_donem_veri_damgasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dersprogrami',
            name='arsivlendi',
            field=models.BooleanField(default=False, help_text="Sene Sonu Geçişi uygulandığında geçmiş eğitim-öğretim yılına ait ders programı yüklemeleri otomatik olarak arşivlenir; arşivlenen kayıtlar artık 'aktif' ders programı olarak gösterilmez, yalnızca Ders Programı Listesi (arşiv) sayfasından eğitim yılı/dönem seçilerek görüntülenebilir.", verbose_name='Arşivlendi'),
        ),
    ]
