# Generated by Django 6.0.3 on 2026-03-08 12:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VeriYukleme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veri Yükleme ve Aktarım",
                "verbose_name_plural": "Veri Yükleme ve Aktarım",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NobetDegisimKaydi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uygulama_tarihi",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("uygulama_baslangic", models.DateTimeField()),
                ("uygulama_bitis", models.DateTimeField()),
                (
                    "aciklama",
                    models.CharField(default="Haftalık nöbet rotasyonu uygulandı", max_length=200),
                ),
            ],
            options={
                "db_table": "nobet_degisim_kaydi",
            },
        ),
        migrations.CreateModel(
            name="NobetOgretmen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uygulama_tarihi",
                    models.DateField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Öğretmenler",
                "verbose_name_plural": "Ders Görevi Olan Öğretmenler",
                "db_table": "nobet_ogretmen",
            },
        ),
        migrations.CreateModel(
            name="NobetPersonel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kimlikno", models.CharField(max_length=11, unique=True)),
                ("adi_soyadi", models.CharField(max_length=100, unique=True)),
                ("brans", models.CharField(max_length=50)),
                (
                    "cinsiyet",
                    models.BooleanField(choices=[(True, "Erkek"), (False, "Kadın")], default=True),
                ),
                ("nobeti_var", models.BooleanField(default=True)),
                ("gorev_tipi", models.CharField(blank=True, max_length=50, null=True)),
                ("sabit_nobet", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Personel",
                "verbose_name_plural": "Personel Listesi",
                "db_table": "nobet_personel",
            },
        ),
        migrations.CreateModel(
            name="NobetIstatistik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toplam_nobet", models.IntegerField(default=0)),
                ("atanmayan_nobet", models.IntegerField(default=0)),
                ("haftalik_ortalama", models.FloatField(default=0.0)),
                ("hafta_sayisi", models.IntegerField(default=0)),
                ("son_nobet_tarihi", models.DateTimeField(blank=True, null=True)),
                ("agirlikli_puan", models.FloatField(default=1.0)),
                (
                    "son_nobet_yeri",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ogretmen",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="istatistikler",
                        to="nobet.nobetogretmen",
                    ),
                ),
            ],
            options={
                "db_table": "nobet_istatistik",
            },
        ),
        migrations.CreateModel(
            name="NobetGorevi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nobet_gun", models.CharField(max_length=10)),
                ("nobet_yeri", models.CharField(max_length=100)),
                (
                    "uygulama_tarihi",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "ogretmen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nobetler",
                        to="nobet.nobetogretmen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nöbet Görevi",
                "verbose_name_plural": "Haftalık Nöbet Görevleri",
                "db_table": "nobet_gorevi",
            },
        ),
        migrations.CreateModel(
            name="NobetGecmisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saat", models.IntegerField(blank=True, null=True)),
                ("sinif", models.CharField(blank=True, max_length=50, null=True)),
                ("devamsiz", models.IntegerField(blank=True, null=True)),
                ("tarih", models.DateTimeField(default=django.utils.timezone.now)),
                ("atandi", models.IntegerField(default=1)),
                (
                    "ogretmen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gecmis",
                        to="nobet.nobetogretmen",
                    ),
                ),
            ],
            options={
                "db_table": "nobet_gecmis",
            },
        ),
        migrations.CreateModel(
            name="NobetAtanamayan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saat", models.IntegerField(blank=True, null=True)),
                ("sinif", models.CharField(blank=True, max_length=50, null=True)),
                ("tarih", models.DateTimeField(default=django.utils.timezone.now)),
                ("atandi", models.IntegerField(default=0)),
                (
                    "ogretmen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atanamayan",
                        to="nobet.nobetogretmen",
                    ),
                ),
            ],
            options={
                "db_table": "nobet_atanamayan",
            },
        ),
        migrations.CreateModel(
            name="Devamsizlik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslangic_tarihi", models.DateTimeField()),
                ("bitis_tarihi", models.DateTimeField(blank=True, null=True)),
                ("aciklama", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "ogretmen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devamsizlik",
                        to="nobet.nobetogretmen",
                    ),
                ),
            ],
            options={
                "db_table": "nobet_devamsizlik",
            },
        ),
        migrations.AddField(
            model_name="nobetogretmen",
            name="personel",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ogretmen",
                to="nobet.nobetpersonel",
            ),
        ),
        migrations.CreateModel(
            name="NobetDersProgrami",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gun", models.CharField(max_length=10)),
                ("giris_saat", models.TimeField()),
                ("cikis_saat", models.TimeField()),
                ("ders_adi", models.CharField(max_length=100)),
                ("sinif", models.CharField(max_length=10)),
                ("sube", models.CharField(max_length=10)),
                ("subeadi", models.CharField(max_length=10)),
                ("ders_saati", models.IntegerField()),
                ("ders_saati_adi", models.CharField(max_length=10)),
                (
                    "uygulama_tarihi",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "ogretmen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dersprogrami",
                        to="nobet.nobetpersonel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ders Programı",
                "verbose_name_plural": "Haftalık Ders Programı",
                "db_table": "nobet_dersprogrami",
            },
        ),
        migrations.CreateModel(
            name="SinifSube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sinif", models.IntegerField()),
                ("sube", models.CharField(max_length=2)),
            ],
            options={
                "verbose_name": "Sınıf Şube",
                "verbose_name_plural": "Sınıf ve Şubeler",
                "unique_together": {("sinif", "sube")},
            },
        ),
    ]
