# Generated by Django 6.0.3 on 2026-03-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nobet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devamsizlik",
            options={
                "verbose_name": "Devamsızlık Kaydı",
                "verbose_name_plural": "Devamsızlık Kayıtları",
            },
        ),
        migrations.AddField(
            model_name="devamsizlik",
            name="devamsiz_tur",
            field=models.IntegerField(
                choices=[
                    (0, "Kısmı Devamsız"),
                    (1, "Raporlu"),
                    (2, "Mazeret İzinli/İzinli"),
                    (3, "Görevli İzinli"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="devamsizlik",
            name="sure",
            field=models.IntegerField(default=1),
        ),
    ]
