# Generated by Django 6.0.3 on 2026-03-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nobet", "0002_alter_devamsizlik_options_devamsizlik_devamsiz_tur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nobetdersprogrami",
            name="gun",
            field=models.CharField(
                choices=[
                    ("Monday", "Pazartesi"),
                    ("Tuesday", "Salı"),
                    ("Wednesday", "Çarşamba"),
                    ("Thursday", "Perşembe"),
                    ("Friday", "Cuma"),
                    ("Saturday", "Cumartesi"),
                    ("Sunday", "Pazar"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="nobetgorevi",
            name="nobet_gun",
            field=models.CharField(
                choices=[
                    ("Monday", "Pazartesi"),
                    ("Tuesday", "Salı"),
                    ("Wednesday", "Çarşamba"),
                    ("Thursday", "Perşembe"),
                    ("Friday", "Cuma"),
                    ("Saturday", "Cumartesi"),
                    ("Sunday", "Pazar"),
                ],
                max_length=10,
            ),
        ),
    ]
