# Generated by Django 6.0.3 on 2026-03-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nobet", "0003_alter_nobetdersprogrami_gun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devamsizlik",
            name="ders_saatleri",
            field=models.CharField(
                default="1,2,3,4,5,6,7,8",
                help_text="Virgülle ayrılmış ders saatleri (Örn: 1,2,3)",
                max_length=50,
            ),
        ),
    ]
