# Generated by Django 6.0.3 on 2026-03-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nobet", "0004_devamsizlik_ders_saatleri"),
    ]

    operations = [
        migrations.AddField(
            model_name="devamsizlik",
            name="gorevlendirme_yapilsin",
            field=models.BooleanField(
                default=True,
                help_text="Bu devamsızlık için boş derslere nöbetçi öğretmen ataması yapılsın mı?",
            ),
        ),
    ]
