# Generated by Django 6.0.3 on 2026-03-11 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nobet", "0005_devamsizlik_gorevlendirme_yapilsin"),
    ]

    operations = [
        migrations.CreateModel(
            name="GunlukNobetCizelgesi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(default=django.utils.timezone.now)),
                ("nobet_yeri", models.CharField(max_length=100)),
                (
                    "ogretmen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gunluk_nobetler",
                        to="nobet.nobetogretmen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Günlük Nöbet Çizelgesi",
                "verbose_name_plural": "Günlük Nöbet Çizelgeleri",
                "db_table": "gunluk_nobet_cizelgesi",
                "unique_together": {("tarih", "ogretmen")},
            },
        ),
    ]
