# Generated by Django 6.0.3 on 2026-03-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nobet", "0006_gunluknobetcizelgesi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devamsizlik",
            name="baslangic_tarihi",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="devamsizlik",
            name="bitis_tarihi",
            field=models.DateField(blank=True, null=True),
        ),
    ]
