# Generated by Django 6.0.3 on 2026-03-14 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nobet", "0009_okulbilgi"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nobetpersonel",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personel",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
    ]
