# Generated by Django 6.0.3 on 2026-03-22 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nobet", "0012_remove_devamsizlik"),
    ]

    operations = [
        migrations.CreateModel(
            name="OkulDonem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "donem",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1. Dönem"), (2, "2. Dönem")], verbose_name="Dönem"
                    ),
                ),
                ("baslangic", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("bitis", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "kurum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donemleri",
                        to="nobet.okulbilgi",
                        verbose_name="Kurum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Okul Dönemi",
                "verbose_name_plural": "Okul Dönemleri",
                "db_table": "okul_donem",
                "ordering": ["donem"],
                "unique_together": {("kurum", "donem")},
            },
        ),
    ]
