# Generated by Django 6.0.3 on 2026-03-22 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nobet", "0013_okuldonem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="okuldonem",
            options={
                "ordering": ["baslangic"],
                "verbose_name": "Okul Dönemi",
                "verbose_name_plural": "Okul Dönemleri",
            },
        ),
        migrations.AlterUniqueTogether(
            name="okuldonem",
            unique_together={("kurum", "baslangic", "bitis")},
        ),
        migrations.CreateModel(
            name="EgitimOgretimYili",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "egitim_yili",
                    models.CharField(
                        help_text="Örnek: 2025-2026",
                        max_length=9,
                        verbose_name="Eğitim-Öğretim Yılı",
                    ),
                ),
                (
                    "egitim_baslangic",
                    models.DateField(verbose_name="Yıl Başlangıç Tarihi"),
                ),
                ("egitim_bitis", models.DateField(verbose_name="Yıl Bitiş Tarihi")),
                (
                    "kurum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="egitim_yillari",
                        to="nobet.okulbilgi",
                        verbose_name="Kurum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eğitim-Öğretim Yılı",
                "verbose_name_plural": "Eğitim-Öğretim Yılları",
                "db_table": "egitim_ogretim_yili",
                "ordering": ["-egitim_yili"],
                "unique_together": {("kurum", "egitim_yili")},
            },
        ),
    ]
