# Generated by Django 6.0.3 on 2026-03-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nobet", "0014_alter_okuldonem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="okulbilgi",
            name="okul_donem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="nobet.okuldonem",
                verbose_name="Aktif Dönem",
            ),
        ),
        migrations.AddField(
            model_name="okulbilgi",
            name="okul_egtyil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="nobet.egitimogretimyili",
                verbose_name="Aktif Eğitim-Öğretim Yılı",
            ),
        ),
    ]
