# Generated by Django 6.0.3 on 2026-03-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nobet", "0015_okulbilgi_okul_donem_okulbilgi_okul_egtyil"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="egitimogretimyili",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="okuldonem",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="egitimogretimyili",
            name="egitim_yili",
            field=models.CharField(
                help_text="Örnek: 2025-2026",
                max_length=9,
                unique=True,
                verbose_name="Eğitim-Öğretim Yılı",
            ),
        ),
        migrations.AlterField(
            model_name="okuldonem",
            name="donem",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1. Dönem"), (2, "2. Dönem")],
                unique=True,
                verbose_name="Dönem",
            ),
        ),
        migrations.RemoveField(
            model_name="egitimogretimyili",
            name="kurum",
        ),
        migrations.RemoveField(
            model_name="okuldonem",
            name="kurum",
        ),
    ]
