# Generated by Django 6.0.3 on 2026-03-22 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nobet", "0016_alter_egitimogretimyili_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="okuldonem",
            name="egitim_yili",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donemleri",
                to="nobet.egitimogretimyili",
                verbose_name="Eğitim-Öğretim Yılı",
            ),
        ),
        migrations.AlterField(
            model_name="okuldonem",
            name="donem",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1. Dönem"), (2, "2. Dönem")], verbose_name="Dönem"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="okuldonem",
            unique_together={("egitim_yili", "donem")},
        ),
    ]
