# Generated by Django 6.0.3 on 2026-03-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nobet", "0021_remove_nobetpersonel"),
    ]

    operations = [
        migrations.CreateModel(
            name="NobetYerleri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nöbet Yeri"
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Nöbet Yeri",
                "verbose_name_plural": "Nöbet Yerleri",
                "db_table": "nobet_yerleri",
                "ordering": ["ad"],
            },
        ),
    ]
