# Generated by Django 6.0.3 on 2026-04-01 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nobet", "0025_nobetgorevi_replace_nobet_yeri_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="MazeretSalonGorevi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "salon",
                    models.CharField(
                        choices=[("Mazeret1", "Mazeret1"), ("Mazeret2", "Mazeret2")],
                        max_length=20,
                        verbose_name="Salon",
                    ),
                ),
                ("saat", models.IntegerField(verbose_name="Ders Saati")),
                ("kayit_zamani", models.DateTimeField(auto_now=True)),
                (
                    "ogretmen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mazeret_gorevleri",
                        to="nobet.nobetogretmen",
                        verbose_name="Görevli Nöbetçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mazeret Salon Görevi",
                "verbose_name_plural": "Mazeret Salon Görevleri",
                "db_table": "nobet_mazeret_salon_gorevi",
                "ordering": ["tarih", "salon", "saat"],
                "unique_together": {("tarih", "salon", "saat")},
            },
        ),
    ]
