# Generated by Django 6.0.3 on 2026-07-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobet', '0026_add_mazeret_salon_gorevi'),
        ('okul', '0018_alter_personel_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunluknobetcizelgesi',
            name='donem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gunluk_nobet_cizelgeleri', to='okul.okuldonem', verbose_name='Dönem'),
        ),
        migrations.AddField(
            model_name='gunluknobetcizelgesi',
            name='egitim_yili',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gunluk_nobet_cizelgeleri', to='okul.egitimogretimyili', verbose_name='Eğitim-Öğretim Yılı'),
        ),
        migrations.AddField(
            model_name='mazeretsalongorevi',
            name='donem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mazeret_salon_gorevleri', to='okul.okuldonem', verbose_name='Dönem'),
        ),
        migrations.AddField(
            model_name='mazeretsalongorevi',
            name='egitim_yili',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mazeret_salon_gorevleri', to='okul.egitimogretimyili', verbose_name='Eğitim-Öğretim Yılı'),
        ),
        migrations.AddField(
            model_name='nobetgorevi',
            name='donem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nobet_gorevleri', to='okul.okuldonem', verbose_name='Dönem'),
        ),
        migrations.AddField(
            model_name='nobetgorevi',
            name='egitim_yili',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nobet_gorevleri', to='okul.egitimogretimyili', verbose_name='Eğitim-Öğretim Yılı'),
        ),
    ]
