# Generated by Django 6.0.3 on 2026-08-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobet', '0028_egitim_yili_donem_veri_damgasi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VeriYukleme',
        ),
    ]
