# Generated by Django 6.0.3 on 2026-09-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobet', '0029_delete_veriyukleme'),
    ]

    operations = [
        migrations.AddField(
            model_name='nobetatanamayan',
            name='arsivlendi',
            field=models.BooleanField(default=False, help_text='Sene Sonu Geçişi uygulandığında geçmiş eğitim-öğretim yılına ait ders doldurma kayıtları otomatik olarak arşivlenir; arşivlenen kayıtlar istatistik hesaplamalarına (bkz. IstatistikService) dahil edilmez.', verbose_name='Arşivlendi'),
        ),
        migrations.AddField(
            model_name='nobetgecmisi',
            name='arsivlendi',
            field=models.BooleanField(default=False, help_text='Sene Sonu Geçişi uygulandığında geçmiş eğitim-öğretim yılına ait ders doldurma kayıtları otomatik olarak arşivlenir; arşivlenen kayıtlar istatistik hesaplamalarına (bkz. IstatistikService) dahil edilmez.', verbose_name='Arşivlendi'),
        ),
    ]
