# Generated by Django 6.0.3 on 2026-09-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobet', '0031_gecmis_gecisleri_arsivle'),
    ]

    operations = [
        migrations.AddField(
            model_name='nobetgorevi',
            name='arsivlendi',
            field=models.BooleanField(default=False, help_text="Sene Sonu Geçişi uygulandığında geçmiş eğitim-öğretim yılına ait yüklenmiş nöbet listeleri otomatik olarak arşivlenir; arşivlenen görevler artık 'aktif' nöbet listesi olarak öğretmenlere gösterilmez, yalnızca Nöbet Listesi (arşiv) sayfasından eğitim yılı/dönem seçilerek görüntülenebilir.", verbose_name='Arşivlendi'),
        ),
    ]
